# Feature Selection:

Now that we have analysed the data, we are ready to choose the features that will be used to train the model.

We first need to choose and preare the group of point-value metrics for the classical ML models.
Then we will need to compute the time-series features derived from the raw data like in 09.2_summarizing_group_of_gait_cycles.ipynb

Once selected, we will analyze the features in detail to choose the ones we will mvoe forward with to the next phase....

In [1]:
import core.constants as c
from core.utils import save_df_as_table_image
import os

import pandas as pd
import numpy as np
from scipy.stats import ttest_ind, chi2_contingency, pearsonr
from sklearn.feature_selection import mutual_info_classif
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.preprocessing import LabelEncoder

In [2]:
data = pd.read_csv(c.RICKD_FEATURE_SELECTION_DATA_FILE)
display(data.head())

data.info(verbose=True)

,id,speed_output,step_width_left,step_width_right,stride_rate_left,stride_rate_right,stride_length_left,stride_length_right,swing_time_left,swing_time_right,...,pelvic_drop_peak_vel_left,pelvic_drop_peak_vel_right,vertical_oscillation_left,vertical_oscillation_right,age,height,weight,gender,dominantleg,is_injured
0,100001_20110531T161051,2.489233,0.123419,0.123419,78.947368,78.947368,1.891817,1.891817,0.4350,0.420,...,-82.090017,-57.417845,96.433793,92.586134,47.0,172.0,61.9,female,left,True
1,100002_20110601T140505,2.722687,0.032922,0.032922,81.632653,81.632653,2.001175,2.001175,0.4450,0.420,...,-57.724685,-60.462411,86.521432,94.945518,37.0,173.4,70.6,male,left,True
2,100003_20110601T095930,2.949904,0.097273,0.097273,78.947368,78.947368,2.241927,2.241927,0.4475,0.445,...,-82.171073,-95.302664,82.680986,76.611379,51.0,186.0,86.5,male,right,True
3,100004_20110203T120721,2.688014,0.011401,0.011401,82.191781,82.191781,1.962250,1.962250,0.4400,0.460,...,-63.319119,-49.646132,92.593339,83.273183,35.0,175.6,59.0,male,left,True
4,100004_20140929T102035,2.928598,0.029021,0.029021,83.333333,82.758621,2.108590,2.123233,0.4200,0.430,...,-32.717949,-52.004473,87.481400,75.091789,39.0,175.0,61.0,male,left,False

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1441 entries, 0 to 1440
Data columns (total 88 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              1441 non-null   object
 1   speed_output                    1441 non-null   float64
 2   step_width_left                 1441 non-null   float64
 3   step_width_right                1441 non-null   float64
 4   stride_rate_left                1441 non-null   float64
 5   stride_rate_right               1441 non-null   float64
 6   stride_length_left              1441 non-null   float64
 7   stride_length_right             1441 non-null   float64
 8   swing_time_left                 1441 non-null   float64
 9   swing_time_right                1441 non-null   float64
 10  stance_time_left                1441 non-null   float64
 11  stance_time_right               1441 non-null   float64
 12  pelvis_peak_drop_angle_left     1441 non-null   float64
 13  pelvis_peak_drop_angle_right    1441 non-null   float64
 14  pelvis_drop_excursion_left      1441 non-null   float64
 15  pelvis_drop_excursion_right     1441 non-null   float64
 16  ankle_df_peak_angle_left        1441 non-null   float64
 17  ankle_df_peak_angle_right       1441 non-null   float64
 18  ankle_eve_peak_angle_left       1441 non-null   float64
 19  ankle_eve_peak_angle_right      1441 non-null   float64
 20  ankle_eve_percent_stance_left   1441 non-null   float64
 21  ankle_eve_percent_stance_right  1441 non-null   float64
 22  ankle_eve_excursion_left        1441 non-null   float64
 23  ankle_eve_excursion_right       1441 non-null   float64
 24  ankle_rot_peak_angle_left       1441 non-null   float64
 25  ankle_rot_peak_angle_right      1441 non-null   float64
 26  ankle_rot_excursion_left        1441 non-null   float64
 27  ankle_rot_excursion_right       1441 non-null   float64
 28  knee_flex_peak_angle_left       1441 non-null   float64
 29  knee_flex_peak_angle_right      1441 non-null   float64
 30  knee_add_peak_angle_left        1441 non-null   float64
 31  knee_add_peak_angle_right       1441 non-null   float64
 32  knee_add_excursion_left         1441 non-null   float64
 33  knee_add_excursion_right        1441 non-null   float64
 34  knee_abd_peak_angle_left        1441 non-null   float64
 35  knee_abd_peak_angle_right       1441 non-null   float64
 36  knee_abd_excursion_left         1441 non-null   float64
 37  knee_abd_excursion_right        1441 non-null   float64
 38  knee_rot_peak_angle_left        1441 non-null   float64
 39  knee_rot_peak_angle_right       1441 non-null   float64
 40  knee_rot_excursion_left         1441 non-null   float64
 41  knee_rot_excursion_right        1441 non-null   float64
 42  hip_ext_peak_angle_left         1441 non-null   float64
 43  hip_ext_peak_angle_right        1441 non-null   float64
 44  hip_add_peak_angle_left         1441 non-null   float64
 45  hip_add_peak_angle_right        1441 non-null   float64
 46  hip_add_excursion_left          1441 non-null   float64
 47  hip_add_excursion_right         1441 non-null   float64
 48  hip_rot_peak_angle_left         1441 non-null   float64
 49  hip_rot_peak_angle_right        1441 non-null   float64
 50  hip_rot_excursion_left          1441 non-null   float64
 51  hip_rot_excursion_right         1441 non-null   float64
 52  foot_prog_angle_left            1441 non-null   float64
 53  foot_prog_angle_right           1441 non-null   float64
 54  foot_ang_at_hs_left             1441 non-null   float64
 55  foot_ang_at_hs_right            1441 non-null   float64
 56  mhw_exc_from_to_left            1441 non-null   float64
 57  mhw_exc_from_to_right           1441 non-null   float64
 58  ankle_eve_peak_vel_left         1441 non-null   float64
 59  ankle_eve_peak_vel_right        1441 non-null   float64
 60  ankle_rot_peak_vel_left         1441 non-null   float64
 61  ankle_rot_peak_vel_right        1441 non-null   float64
 62  knee_abd_peak_vel_left          1441 non-null   float64
 63  knee_abd_peak_vel_right         1441 non-null   float64
 64  knee_add_peak_vel_left          1441 non-null   float64
 65  knee_add_peak_vel_right         1441 non-null   float64
 66  hip_abd_peak_vel_left           1441 non-null   float64
 67  hip_abd_peak_vel_right          1441 non-null   float64
 68  knee_rot_peak_vel_left          1441 non-null   float64
 69  knee_rot_peak_vel_right         1441 non-null   float64
 70  hip_rot_peak_vel_left           1441 non-null   float64
 71  hip_rot_peak_vel_right          1441 non-null   float64
 72  pronation_onset_left            1441 non-null   int64
 73  pronation_onset_right           1441 non-null   int64
 74  supination_timing_left          1441 non-null   int64
 75  supination_timing_right         1441 non-null   int64
 76  hip_add_peak_vel_left           1441 non-null   float64
 77  hip_add_peak_vel_right          1441 non-null   float64
 78  pelvic_drop_peak_vel_left       1441 non-null   float64
 79  pelvic_drop_peak_vel_right      1441 non-null   float64
 80  vertical_oscillation_left       1441 non-null   float64
 81  vertical_oscillation_right      1441 non-null   float64
 82  age                             1441 non-null   float64
 83  height                          1441 non-null   float64
 84  weight                          1441 non-null   float64
 85  gender                          1441 non-null   object
 86  dominantleg                     1441 non-null   object
 87  is_injured                      1441 non-null   bool
dtypes: bool(1), float64(80), int64(4), object(3)
memory usage: 981.0+ KB

In [3]:
def cohens_d(x, y):
    nx, ny = len(x), len(y)
    dof = nx + ny - 2
    pooled_std = np.sqrt(((nx - 1) * np.var(x, ddof=1) + (ny - 1) * np.var(y, ddof=1)) / dof)
    return (np.mean(x) - np.mean(y)) / pooled_std

def cramers_v(confusion_matrix):
    chi2 = chi2_contingency(confusion_matrix)[0]
    n = confusion_matrix.sum().sum()
    phi2 = chi2 / n
    r, k = confusion_matrix.shape
    phi2corr = max(0, phi2 - ((k - 1)*(r - 1))/(n - 1))
    rcorr = r - ((r - 1)**2)/(n - 1)
    kcorr = k - ((k - 1)**2)/(n - 1)
    return np.sqrt(phi2corr / min((kcorr - 1), (rcorr - 1)))

def calculate_vif(df):
    vif_data = pd.DataFrame()
    vif_data['feature'] = df.columns
    vif_data['VIF'] = [variance_inflation_factor(df.values, i) for i in range(df.shape[1])]
    return vif_data

# ==============================
# Main analysis function
# ==============================

def predictor_analysis(df, target, cat_threshold=10):
    results = []
    
    y = df[target]
    y_num = LabelEncoder().fit_transform(y)  # Binary 0/1 target
    
    for col in df.columns:
        if col == target:
            continue
        
        series = df[col].dropna()
        
        # Detect variable type
        if pd.api.types.is_numeric_dtype(series) and df[col].nunique() > cat_threshold:
            # Continuous variable
            group0 = df[df[target] == y.unique()[0]][col]
            group1 = df[df[target] == y.unique()[1]][col]
            
            # t-test
            t_pval = ttest_ind(group0, group1, equal_var=False).pvalue
            d = cohens_d(group0, group1)
            
            # Pearson
            r_val, r_pval = pearsonr(df[col], y_num)
            
            # Mutual Information
            mi_val = mutual_info_classif(df[[col]], y_num, discrete_features=False)[0]
            
            results.append({
                'predictor': col,
                'type': 'continuous',
                't-test p': t_pval,
                "Cohen's d": d,
                'Pearson r': r_val,
                'Pearson p': r_pval,
                'Mutual Info': mi_val
            })
        
        else:
            # Categorical variable
            contingency = pd.crosstab(df[col], y)
            chi2_pval = chi2_contingency(contingency)[1]
            cramer_v = cramers_v(contingency)
            mi_val = mutual_info_classif(pd.get_dummies(df[[col]]), y_num, discrete_features=True)[0]
            
            results.append({
                'predictor': col,
                'type': 'categorical',
                'Chi2 p': chi2_pval,
                "Cramer's V": cramer_v,
                'Mutual Info': mi_val
            })
    
    results_df = pd.DataFrame(results)
    
    # VIF for continuous predictors
    continuous_cols = [col for col in df.columns if col != target and pd.api.types.is_numeric_dtype(df[col]) and df[col].nunique() > cat_threshold]
    if continuous_cols:
        vif_df = calculate_vif(df[continuous_cols].fillna(0))
    else:
        vif_df = pd.DataFrame(columns=['feature', 'VIF'])
    
    return results_df, vif_df

In [4]:
excluded_columns = ["id"]
results_df, vif_df = predictor_analysis(data.drop(excluded_columns, axis=1), target='is_injured')

with pd.option_context('display.max_rows', None):
    display(results_df.sort_values('Mutual Info', ascending=False))
    display(vif_df.sort_values('VIF', ascending=False))

save_df_as_table_image(results_df, os.path.join(c.RICKD_RESULTS_FOLDER, 'predictor_analysis_results.png'))
save_df_as_table_image(vif_df, os.path.join(c.RICKD_RESULTS_FOLDER, 'predictor_analysis_VIF.png'))

/Users/adrianzapaterreig/Documents/Personal/TFM/rickd-analysis/.venv/lib/python3.11/site-packages/statsmodels/stats/outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

,predictor,type,t-test p,Cohen's d,Pearson r,Pearson p,Mutual Info,Chi2 p,Cramer's V
27,knee_flex_peak_angle_left,continuous,0.002728,-0.173161,-0.077065,0.003420,0.037381,NaN,NaN
83,weight,continuous,0.435431,0.044333,0.019785,0.452968,0.031274,NaN,NaN
54,foot_ang_at_hs_right,continuous,0.096196,0.099508,0.044374,0.092213,0.020574,NaN,NaN
75,hip_add_peak_vel_left,continuous,0.437795,-0.045875,-0.020473,0.437408,0.019435,NaN,NaN
65,hip_abd_peak_vel_left,continuous,0.457402,-0.043910,-0.019597,0.457283,0.019143,NaN,NaN
44,hip_add_peak_angle_right,continuous,0.093254,0.093717,0.041797,0.112754,0.018823,NaN,NaN
34,knee_abd_peak_angle_right,continuous,0.030757,-0.123134,-0.054881,0.037244,0.018244,NaN,NaN
0,speed_output,continuous,0.006008,-0.156037,-0.069483,0.008327,0.017508,NaN,NaN
67,knee_rot_peak_vel_left,continuous,0.978988,0.001598,0.000713,0.978418,0.017031,NaN,NaN
23,ankle_rot_peak_angle_left,continuous,0.640648,0.028601,0.012766,0.628242,0.016267,NaN,NaN
56,mhw_exc_from_to_right,continuous,0.142144,-0.081690,-0.036440,0.166802,0.015761,NaN,NaN
38,knee_rot_peak_angle_right,continuous,0.004628,0.171350,0.076264,0.003771,0.015094,NaN,NaN
39,knee_rot_excursion_left,continuous,0.029263,0.130609,0.058202,0.027151,0.014673,NaN,NaN
81,age,continuous,0.073294,0.110538,0.049282,0.061446,0.014061,NaN,NaN
12,pelvis_peak_drop_angle_right,continuous,0.401404,-0.047894,-0.021374,0.417506,0.013039,NaN,NaN
47,hip_rot_peak_angle_left,continuous,0.000125,-0.227449,-0.101009,0.000123,0.012512,NaN,NaN
33,knee_abd_peak_angle_left,continuous,0.052110,-0.115175,-0.051344,0.051340,0.012113,NaN,NaN
16,ankle_df_peak_angle_right,continuous,0.545194,-0.033886,-0.015124,0.566197,0.011443,NaN,NaN
7,swing_time_left,continuous,0.461640,-0.043649,-0.019480,0.459959,0.010853,NaN,NaN
32,knee_add_excursion_right,continuous,0.170652,0.080436,0.035882,0.173406,0.010664,NaN,NaN
9,stance_time_left,continuous,0.000045,0.236591,0.105025,0.000065,0.010172,NaN,NaN
2,step_width_right,continuous,0.868227,0.009614,0.004291,0.870706,0.010075,NaN,NaN
1,step_width_left,continuous,0.868227,0.009614,0.004291,0.870706,0.010075,NaN,NaN
74,supination_timing_right,continuous,0.093549,0.099463,0.044354,0.092360,0.009853,NaN,NaN
57,ankle_eve_peak_vel_left,continuous,0.016713,0.138763,0.061822,0.018925,0.009294,NaN,NaN
66,hip_abd_peak_vel_right,continuous,0.919730,-0.005844,-0.002609,0.921184,0.009062,NaN,NaN
78,pelvic_drop_peak_vel_right,continuous,0.036877,-0.119337,-0.053194,0.043492,0.008898,NaN,NaN
76,hip_add_peak_vel_right,continuous,0.306409,0.060980,0.027210,0.301978,0.007835,NaN,NaN
69,hip_rot_peak_vel_left,continuous,0.832288,0.012479,0.005570,0.832678,0.007041,NaN,NaN
4,stride_rate_right,continuous,0.042676,-0.114665,-0.051117,0.052378,0.006456,NaN,NaN
22,ankle_eve_excursion_right,continuous,0.566598,0.033466,0.014937,0.571023,0.006230,NaN,NaN
18,ankle_eve_peak_angle_right,continuous,0.685630,-0.022608,-0.010091,0.701911,0.005964,NaN,NaN
59,ankle_rot_peak_vel_left,continuous,0.344034,0.056379,0.025158,0.339910,0.005828,NaN,NaN
11,pelvis_peak_drop_angle_left,continuous,0.403164,0.048040,0.021439,0.416087,0.005391,NaN,NaN
77,pelvic_drop_peak_vel_left,continuous,0.344344,-0.055956,-0.024970,0.343542,0.004877,NaN,NaN
63,knee_add_peak_vel_left,continuous,0.727669,-0.021055,-0.009398,0.721498,0.004564,NaN,NaN
70,hip_rot_peak_vel_right,continuous,0.743943,0.019250,0.008592,0.744509,0.003911,NaN,NaN
62,knee_abd_peak_vel_right,continuous,0.962896,0.002630,0.001174,0.964482,0.003452,NaN,NaN
30,knee_add_peak_angle_right,continuous,0.069450,-0.101779,-0.045385,0.085029,0.003385,NaN,NaN
3,stride_rate_left,continuous,0.041088,-0.115696,-0.051575,0.050296,0.003031,NaN,NaN
19,ankle_eve_percent_stance_left,continuous,0.575239,0.032630,0.014564,0.580676,0.002777,NaN,NaN
51,foot_prog_angle_left,continuous,0.294950,0.062329,0.027812,0.291412,0.002576,NaN,NaN
24,ankle_rot_peak_angle_right,continuous,0.628920,-0.027507,-0.012277,0.641453,0.001839,NaN,NaN
52,foot_prog_angle_right,continuous,0.466241,0.041901,0.018700,0.478128,0.001693,NaN,NaN
31,knee_add_excursion_left,continuous,0.126734,0.088532,0.039488,0.134063,0.001208,NaN,NaN
60,ankle_rot_peak_vel_right,continuous,0.725365,0.020381,0.009097,0.730057,0.000757,NaN,NaN
61,knee_abd_peak_vel_left,continuous,0.475987,-0.042560,-0.018994,0.471236,0.000684,NaN,NaN
53,foot_ang_at_hs_left,continuous,0.060535,0.110541,0.049283,0.061440,0.000445,NaN,NaN
85,dominantleg,categorical,NaN,NaN,NaN,NaN,0.000222,0.577288,0.0
84,gender,categorical,NaN,NaN,NaN,NaN,0.000073,0.689555,0.0
49,hip_rot_excursion_left,continuous,0.377694,-0.051531,-0.022996,0.383039,0.000000,NaN,NaN
13,pelvis_drop_excursion_left,continuous,0.961368,0.002798,0.001249,0.962217,0.000000,NaN,NaN
17,ankle_eve_peak_angle_left,continuous,0.082028,0.096312,0.042952,0.103143,0.000000,NaN,NaN
71,pronation_onset_left,continuous,0.934172,0.004850,0.002165,0.934563,0.000000,NaN,NaN
72,pronation_onset_right,continuous,0.895604,0.007730,0.003451,0.895877,0.000000,NaN,NaN
73,supination_timing_left,continuous,0.896146,0.007672,0.003425,0.896656,0.000000,NaN,NaN
15,ankle_df_peak_angle_left,continuous,0.191113,-0.073362,-0.032730,0.214353,0.000000,NaN,NaN
14,pelvis_drop_excursion_right,continuous,0.157703,-0.080758,-0.036025,0.171692,0.000000,NaN,NaN
10,stance_time_right,continuous,0.000486,0.199452,0.088680,0.000752,0.000000,NaN,NaN
68,knee_rot_peak_vel_right,continuous,0.148416,0.086039,0.038378,0.145362,0.000000,NaN,NaN
8,swing_time_right,continuous,0.828845,-0.012553,-0.005603,0.831696,0.000000,NaN,NaN
79,vertical_oscillation_left,continuous,0.264354,-0.064066,-0.028586,0.278183,0.000000,NaN,NaN
80,vertical_oscillation_right,continuous,0.813944,-0.013315,-0.005943,0.821650,0.000000,NaN,NaN
6,stride_length_right,continuous,0.021237,-0.135171,-0.060228,0.022233,0.000000,NaN,NaN
82,height,continuous,0.628922,0.029018,0.012952,0.623245,0.000000,NaN,NaN
5,stride_length_left,continuous,0.021744,-0.134731,-0.060032,0.022671,0.000000,NaN,NaN
20,ankle_eve_percent_stance_right,continuous,0.677716,0.024451,0.010914,0.678911,0.000000,NaN,NaN
21,ankle_eve_excursion_left,continuous,0.117944,0.091357,0.040746,0.122097,0.000000,NaN,NaN
50,hip_rot_excursion_right,continuous,0.544537,-0.036339,-0.016219,0.538438,0.000000,NaN,NaN
25,ankle_rot_excursion_left,continuous,0.376576,0.051900,0.023161,0.379643,0.000000,NaN,NaN
48,hip_rot_peak_angle_right,continuous,0.116572,-0.095423,-0.042556,0.106357,0.000000,NaN,NaN
46,hip_add_excursion_right,continuous,0.193441,0.077827,0.034719,0.187769,0.000000,NaN,NaN
45,hip_add_excursion_left,continuous,0.573033,-0.033600,-0.014996,0.569485,0.000000,NaN,NaN
42,hip_ext_peak_angle_right,continuous,0.001048,0.200132,0.088980,0.000721,0.000000,NaN,NaN
55,mhw_exc_from_to_left,continuous,0.459851,-0.041061,-0.018326,0.486989,0.000000,NaN,NaN
41,hip_ext_peak_angle_left,continuous,0.016315,0.146269,0.065152,0.013372,0.000000,NaN,NaN
40,knee_rot_excursion_right,continuous,0.050552,0.117734,0.052481,0.046387,0.000000,NaN,NaN
58,ankle_eve_peak_vel_right,continuous,0.174554,0.078000,0.034796,0.186788,0.000000,NaN,NaN
37,knee_rot_peak_angle_left,continuous,0.000126,0.231069,0.102600,0.000096,0.000000,NaN,NaN
36,knee_abd_excursion_right,continuous,0.983332,-0.001215,-0.000542,0.983587,0.000000,NaN,NaN
35,knee_abd_excursion_left,continuous,0.946209,-0.004069,-0.001816,0.945083,0.000000,NaN,NaN
29,knee_add_peak_angle_left,continuous,0.239053,-0.068109,-0.030388,0.248982,0.000000,NaN,NaN
28,knee_flex_peak_angle_right,continuous,0.000070,-0.228736,-0.101574,0.000112,0.000000,NaN,NaN
64,knee_add_peak_vel_right,continuous,0.076608,0.101924,0.045449,0.084586,0.000000,NaN,NaN
26,ankle_rot_excursion_right,continuous,0.473938,0.041803,0.018657,0.479153,0.000000,NaN,NaN
43,hip_add_peak_angle_left,continuous,0.007126,0.151640,0.067534,0.010338,0.000000,NaN,NaN

                           feature           VIF
2                 step_width_right           inf
1                  step_width_left           inf
6              stride_length_right  2.817044e+06
5               stride_length_left  2.815172e+06
3                 stride_rate_left  2.799797e+06
4                stride_rate_right  2.798121e+06
8                 swing_time_right  1.669192e+04
7                  swing_time_left  1.668037e+04
0                     speed_output  1.145113e+04
10               stance_time_right  8.215843e+03
9                 stance_time_left  8.057869e+03
34       knee_abd_peak_angle_right  5.142616e+03
33        knee_abd_peak_angle_left  4.904888e+03
30       knee_add_peak_angle_right  1.471312e+03
29        knee_add_peak_angle_left  1.360400e+03
82                          height  1.081710e+03
36        knee_abd_excursion_right  1.027656e+03
35         knee_abd_excursion_left  9.176927e+02
31         knee_add_excursion_left  4.577578e+02
27       knee_flex_peak_angle_left  3.529958e+02
28      knee_flex_peak_angle_right  3.485331e+02
32        knee_add_excursion_right  2.498114e+02
80      vertical_oscillation_right  1.882615e+02
15        ankle_df_peak_angle_left  1.835587e+02
16       ankle_df_peak_angle_right  1.820356e+02
79       vertical_oscillation_left  1.760465e+02
57         ankle_eve_peak_vel_left  1.556251e+02
21        ankle_eve_excursion_left  1.505187e+02
58        ankle_eve_peak_vel_right  1.466946e+02
22       ankle_eve_excursion_right  1.336874e+02
46         hip_add_excursion_right  1.073677e+02
78      pelvic_drop_peak_vel_right  1.010369e+02
14     pelvis_drop_excursion_right  1.009949e+02
74         supination_timing_right  9.980936e+01
83                          weight  9.721788e+01
13      pelvis_drop_excursion_left  9.174610e+01
77       pelvic_drop_peak_vel_left  9.037636e+01
45          hip_add_excursion_left  8.967536e+01
73          supination_timing_left  8.006046e+01
39         knee_rot_excursion_left  7.904203e+01
40        knee_rot_excursion_right  7.559727e+01
76          hip_add_peak_vel_right  6.520096e+01
43         hip_add_peak_angle_left  6.387902e+01
75           hip_add_peak_vel_left  5.850910e+01
44        hip_add_peak_angle_right  5.811376e+01
71            pronation_onset_left  5.807340e+01
19   ankle_eve_percent_stance_left  5.323791e+01
67          knee_rot_peak_vel_left  5.053610e+01
68         knee_rot_peak_vel_right  4.960327e+01
20  ankle_eve_percent_stance_right  4.919033e+01
25        ankle_rot_excursion_left  4.720211e+01
26       ankle_rot_excursion_right  4.541071e+01
59         ankle_rot_peak_vel_left  4.142866e+01
72           pronation_onset_right  4.077850e+01
38       knee_rot_peak_angle_right  4.054649e+01
60        ankle_rot_peak_vel_right  3.954540e+01
54            foot_ang_at_hs_right  3.915617e+01
53             foot_ang_at_hs_left  3.472668e+01
37        knee_rot_peak_angle_left  3.075705e+01
42        hip_ext_peak_angle_right  2.814301e+01
48        hip_rot_peak_angle_right  2.692921e+01
41         hip_ext_peak_angle_left  2.579313e+01
62         knee_abd_peak_vel_right  2.473676e+01
47         hip_rot_peak_angle_left  2.334252e+01
61          knee_abd_peak_vel_left  2.317313e+01
11     pelvis_peak_drop_angle_left  2.209963e+01
12    pelvis_peak_drop_angle_right  2.126814e+01
63          knee_add_peak_vel_left  1.937817e+01
81                             age  1.881528e+01
64         knee_add_peak_vel_right  1.777321e+01
65           hip_abd_peak_vel_left  1.774266e+01
52           foot_prog_angle_right  1.664033e+01
66          hip_abd_peak_vel_right  1.599137e+01
51            foot_prog_angle_left  1.303540e+01
70          hip_rot_peak_vel_right  1.048122e+01
17       ankle_eve_peak_angle_left  9.749699e+00
18      ankle_eve_peak_angle_right  8.807158e+00
69           hip_rot_peak_vel_left  8.454928e+00
56           mhw_exc_from_to_right  7.112359e+00
23       ankle_rot_peak_angle_left  6.848094e+00
55            mhw_exc_from_to_left  6.270467e+00
24      ankle_rot_peak_angle_right  6.116735e+00
50         hip_rot_excursion_right  5.528819e+00
49          hip_rot_excursion_left  4.718516e+00