# Results and visualisations for Chapter 3 Section Exploratory Data Analysis:

In [20]:
from core.matlab_data_loader import MatlabDataLoader
import kineticstoolkit as ktk
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import core.constants as c

In [ ]:
loader = MatlabDataLoader()
cleaned_data = loader.get_session_data_full_cleaned()

In [22]:
missing_percent = cleaned_data.isnull().mean() * 100
print("Percentage of missing values per column:")
with pd.option_context("display.max_rows", None):
    display(missing_percent.sort_values(ascending=False))

Percentage of missing values per column:

YrPR                           76.801310
RaceTimeSecs                   75.709607
NumRaces                       72.489083
RaceTimeHrs                    69.705240
RaceTimeMins                   61.735808
YrsRunning                     31.004367
DominantLeg                    19.213974
RaceDistance                   18.449782
Activities                     17.248908
Level                          14.683406
injury_severity_code            4.366812
injury_severity_value           4.366812
r_vertical_oscillation          0.709607
l_vertical_oscillation          0.709607
datestring                      0.545852
Height                          0.436681
Weight                          0.272926
Gender                          0.054585
age                             0.054585
r_hip_ext_peak_angle            0.000000
r_knee_abd_excursion            0.000000
r_knee_rot_peak_angle           0.000000
r_knee_rot_excursion            0.000000
r_hip_add_excursion             0.000000
r_hip_add_peak_angle            0.000000
r_hip_rot_peak_angle            0.000000
r_foot_prog_angle               0.000000
r_hip_rot_excursion             0.000000
id                              0.000000
r_ankle_eve_excursion           0.000000
r_knee_abd_peak_angle           0.000000
r_knee_add_excursion            0.000000
r_knee_add_peak_angle           0.000000
r_knee_flex_peak_angle          0.000000
r_ankle_rot_excursion           0.000000
r_ankle_rot_peak_angle          0.000000
r_mhw_exc_from_to               0.000000
r_ankle_eve_percent_stance      0.000000
r_ankle_eve_peak_angle          0.000000
r_ankle_df_peak_angle           0.000000
r_foot_ang_at_hs                0.000000
r_peak_hip_add_velocity         0.000000
r_ankle_eve_peak_vel            0.000000
injury2_code                    0.000000
has_no_injury                   0.000000
injured_side2_code              0.000000
injured_side_code               0.000000
injured_joint2_code             0.000000
injured_joint_code              0.000000
injury2_name                    0.000000
injury_name                     0.000000
injury2_desc                    0.000000
injury_desc                     0.000000
injury_code                     0.000000
r_ankle_rot_peak_vel            0.000000
r_peak_pelvic_drop_velocity     0.000000
r_pelvis_peak_drop_angle        0.000000
r_pronation_offset              0.000000
r_pronation_onset               0.000000
r_hip_rot_peak_vel              0.000000
r_knee_rot_peak_vel             0.000000
r_hip_abd_peak_vel              0.000000
r_knee_add_peak_vel             0.000000
r_knee_abd_peak_vel             0.000000
r_pelvis_drop_excursion         0.000000
l_peak_hip_add_velocity         0.000000
r_stance_time                   0.000000
r_swing_time                    0.000000
l_knee_abd_excursion            0.000000
l_knee_abd_peak_angle           0.000000
l_knee_add_excursion            0.000000
l_knee_add_peak_angle           0.000000
l_knee_flex_peak_angle          0.000000
l_ankle_rot_excursion           0.000000
l_ankle_rot_peak_angle          0.000000
l_ankle_eve_excursion           0.000000
l_ankle_eve_percent_stance      0.000000
l_ankle_eve_peak_angle          0.000000
l_ankle_df_peak_angle           0.000000
l_pelvis_drop_excursion         0.000000
l_pelvis_peak_drop_angle        0.000000
l_stance_time                   0.000000
l_swing_time                    0.000000
l_stride_length                 0.000000
l_stride_rate                   0.000000
l_step_width                    0.000000
session_file_path               0.000000
speed_r                         0.000000
filename                        0.000000
l_knee_rot_peak_angle           0.000000
l_knee_rot_excursion            0.000000
l_hip_ext_peak_angle            0.000000
l_hip_abd_peak_vel              0.000000
r_stride_length                 0.000000
r_stride_rate                   0.000000
r_step_width                    0.000000
l_peak_pelvic_drop_velocity     0.000000
sub_id                          0.000000
l_pronation_offset              0.000000
l_pronation_onset               0.000000
l_hip_rot_peak_vel              0.000000
l_knee_rot_peak_vel             0.000000
l_knee_add_peak_vel             0.000000
l_hip_add_peak_angle            0.000000
l_knee_abd_peak_vel             0.000000
l_ankle_rot_peak_vel            0.000000
l_ankle_eve_peak_vel            0.000000
l_mhw_exc_from_to               0.000000
l_foot_ang_at_hs                0.000000
l_foot_prog_angle               0.000000
l_hip_rot_excursion             0.000000
l_hip_rot_peak_angle            0.000000
l_hip_add_excursion             0.000000
is_injured                      0.000000
dtype: float64

In [23]:
# Find columns with less than 1% missing values
low_missing_cols = missing_percent[missing_percent < 1].index.tolist()

# Count rows that have non-missing values for all these columns
num_complete_rows = cleaned_data[low_missing_cols].notnull().all(axis=1).sum()

print(f"Number of rows with non-missing values for all columns with <1% missing: {num_complete_rows}")
percent_complete_rows = (num_complete_rows / len(cleaned_data)) * 100
print(f"Percentage of rows with non-missing values for all columns with <1% missing: {percent_complete_rows:.2f}%")

Number of rows with non-missing values for all columns with <1% missing: 1799
Percentage of rows with non-missing values for all columns with <1% missing: 98.20%

In [24]:
run_data_meta_cleaned = pd.read_csv(c.RICKD_RUNNING_METADATA_CLEANED_FILE)
descriptive_variables = pd.read_csv(c.RICKD_DESCRIPTIVE_VARIABLES_FILE).drop(columns=['session_file_path', 'subject_id'])

session_data_full = pd.merge(run_data_meta_cleaned, descriptive_variables, on='id', how='left')
display(session_data_full)

,id,sub_id,datestring,filename,speed_r,age,Height,Weight,Gender,DominantLeg,...,r_knee_add_vel_percent_stance,r_hip_abd_peak_vel,r_hip_abd_vel_percent_stance,r_knee_rot_peak_vel,r_hip_rot_peak_vel,r_pronation_onset,r_pronation_offset,r_peak_hip_add_velocity,r_peak_pelvic_drop_velocity,r_vertical_oscillation
0,100433_20101005t132240,100433,2010-10-05 13:22:40,20101005t132240.json,1.610861,53,NaN,NaN,unknown,NaN,...,0,-17.620105,0,121.078813,95.598653,17,57,59.323001,-75.058744,51.466247
1,100434_20101117t132240,100434,2010-11-17 13:22:40,20101117t132240.json,2.237294,51,NaN,NaN,female,NaN,...,0,-42.544797,0,292.718838,17.255165,8,53,183.573751,-96.178927,62.307667
2,100537_20120703t102550,100537,2012-07-03 10:25:50,20120703t102550.json,2.127441,255,173.1,67.6,female,right,...,0,-55.286282,0,318.798151,201.561725,13,56,257.430836,-62.804925,81.753809
3,100560_20120717t103748,100560,2012-07-17 10:37:48,20120717t103748.json,2.657365,33,179.3,83.0,female,right,...,0,-109.157604,0,349.195418,84.881142,20,55,320.445059,-141.687354,111.686204
4,101481_20120717t105021,101481,2012-07-17 10:50:21,20120717t105021.json,2.625088,32,176.3,58.6,female,NaN,...,0,-24.314138,0,226.067684,93.835737,17,57,169.271213,-49.506248,99.045820
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1827,200986_20150312t143944,200986,2015-03-12 14:39:44,20150312t143944.json,4.876998,20,174.0,56.8,female,right,...,0,-64.155468,0,256.832528,56.272377,26,55,113.244646,-35.757575,84.589713
1828,200987_20150312t160840,200987,2015-03-12 16:08:40,20150312t160840.json,2.765022,50,164.0,60.0,female,right,...,0,-53.086396,0,153.266603,62.976728,18,52,171.902428,-70.457833,68.524480
1829,201100_20150409t155915,201100,2015-04-09 15:59:15,20150409t155915.json,2.790966,52,170.0,80.0,male,right,...,0,-67.818836,0,240.909620,15.134823,19,68,203.683223,-120.697186,86.710600
1830,201101_20150413t143152,201101,2015-04-13 14:31:52,20150413t143152.json,2.828602,21,162.0,65.5,male,right,...,0,-21.455733,0,252.971737,72.610820,17,50,168.473505,-79.974041,67.343927
1831,201099_20150414t092041,201099,2015-04-14 09:20:41,20150414t092041.json,2.514918,57,165.5,74.1,female,right,...,0,-3.849964,0,240.324225,32.522741,14,55,232.654680,-103.766594,74.464189

In [25]:
display(cleaned_data[cleaned_data['sub_id'].isin([300375, 100234])])

,id,sub_id,datestring,filename,speed_r,age,Height,Weight,Gender,DominantLeg,...,injury_desc,injury2_desc,injury_name,injury2_name,injured_joint_code,injured_joint2_code,injured_side_code,injured_side2_code,has_no_injury,is_injured
1150,100234_20090909T201123,100234,2011-10-06 13:21:51,20090909t201123.json,2.504259,40.0,165.3,56.4,female,left,...,No injury has been diagnosed.,No injury has been diagnosed.,no injury,no injury,no_injury,no_injury,right,right,True,False
1355,100234_20120518T094409,100234,2012-05-18 09:44:09,20120518t094409.json,2.278154,41.0,165.0,57.3,female,right,...,No injury has been diagnosed.,No injury has been diagnosed.,no injury,no injury,no_injury,no_injury,right,right,True,False
1492,300375_20140502T073048,300375,2014-05-02 07:30:48,20140502t073048.json,2.923722,27.0,168.0,51.0,female,left,...,General sensation of discomfort without speci...,General sensation of discomfort without speci...,pain,pain,foot,foot,right,left,False,True
1493,300375_20140502T074159,300375,2014-05-02 07:41:59,20140502t074159.json,2.961155,27.0,168.0,51.0,female,left,...,General sensation of discomfort without speci...,General sensation of discomfort without speci...,pain,pain,foot,foot,right,left,False,True

In [26]:
# Check for special cases in discrete with metadata
ids_to_check = [
    "100234_20090909T201123",
    "100234_20120518T094409",
    "200375_20140501T142737",
    "200375_20140509T070651",
    "300375_20140502T073048",
    "300375_20140502T074159",
]
full_m_data = loader.get_discrete_variables()
full_m_data["sub_id"] = full_m_data["ID"].str.split("_").str[0]
full_m_data[full_m_data['ID'].isin(ids_to_check)][["ID", "sub_id", "Step_Width_Left", "Step_Width_Right"]].sort_values(by="sub_id")

                          ID  sub_id  Step_Width_Left  Step_Width_Right
182   100234_20090909T201123  100234         0.034276          0.034276
183   100234_20120518T094409  100234         0.050795          0.050795
1730  200375_20140501T142737  200375         0.065933          0.065933
1732  200375_20140509T070651  200375         0.070839          0.070839

In [27]:
# Check for special cases in discrete with metadata
full_c_data = loader.get_session_data_full_cleaned()
full_c_data[full_c_data['sub_id'].isin([200375, 300375, 100234])][["id", "sub_id", "age", "l_step_width", "r_step_width"]].sort_values(by="sub_id")

                          id  sub_id   age  l_step_width  r_step_width
1150  100234_20090909T201123  100234  40.0      0.034276      0.034276
1355  100234_20120518T094409  100234  41.0      0.050795      0.050795
1491  200375_20140501T142737  200375  51.0      0.065933      0.065933
1494  200375_20140509T070651  200375  51.0      0.070839      0.070839
1492  300375_20140502T073048  300375  27.0      0.005804      0.005804
1493  300375_20140502T074159  300375  27.0      0.009988      0.009988

Synthetic subject is one of the 19 sessions that failed to be processed.

In [28]:
print(len(loader.get_discrete_variables()))
print(len(loader.get_session_data_full_cleaned()))
print(len(loader.get_discrete_with_metadata()))

# Find the id of the row that is missing in get_discrete_with_metadata compared to get_discrete_variables
disc_vars = loader.get_discrete_variables()
disc_with_meta = loader.get_discrete_with_metadata(refresh_cache=True)
clean_vars = loader.get_session_data_full_cleaned(refresh_cache=True)

missing_ids = set(clean_vars['id']) - set(disc_with_meta['ID'])
print("ID(s) missing in get_discrete_with_metadata:", missing_ids)
print(len(missing_ids))

1813
1832
1813
ID(s) missing in get_discrete_with_metadata: {'200365_20141007T122631', '101164_20140811T103911', '200332_20140901T182827', '201091_20150408T175440', '200241_20140204T123534', '200365_20141007T112302', '200268_20140505T143806', '100390_20120315T133207', '100313_20110209T125643', '200251_20140408T134209', '200326_20140822T084657', '200283_20140619T133016', '100218_20110921T141851', '100319_20110408T122343', '200250_20140407T113504', '200253_20140414T121747', '101146_20140707T124250', '300375_20140502T073048', '101413_20150402T122006'}
19

In [29]:
print(cleaned_data.loc[cleaned_data['r_vertical_oscillation'].isnull()].to_string())

                          id  sub_id           datestring              filename   speed_r   age  Height  Weight  Gender DominantLeg                            Activities         Level  YrsRunning              RaceDistance  RaceTimeHrs  RaceTimeMins  RaceTimeSecs    YrPR  NumRaces            session_file_path  l_step_width  l_stride_rate  l_stride_length  l_swing_time  l_stance_time  l_pelvis_peak_drop_angle  l_pelvis_drop_excursion  l_ankle_df_peak_angle  l_ankle_eve_peak_angle  l_ankle_eve_percent_stance  l_ankle_eve_excursion  l_ankle_rot_peak_angle  l_ankle_rot_excursion  l_knee_flex_peak_angle  l_knee_add_peak_angle  l_knee_add_excursion  l_knee_abd_peak_angle  l_knee_abd_excursion  l_knee_rot_peak_angle  l_knee_rot_excursion  l_hip_ext_peak_angle  l_hip_add_peak_angle  l_hip_add_excursion  l_hip_rot_peak_angle  l_hip_rot_excursion  l_foot_prog_angle  l_foot_ang_at_hs  l_mhw_exc_from_to  l_ankle_eve_peak_vel  l_ankle_rot_peak_vel  l_knee_abd_peak_vel  l_knee_add_peak_vel  l_hip_abd_peak_vel  l_knee_rot_peak_vel  l_hip_rot_peak_vel  l_pronation_onset  l_pronation_offset  l_peak_hip_add_velocity  l_peak_pelvic_drop_velocity  l_vertical_oscillation  r_step_width  r_stride_rate  r_stride_length  r_swing_time  r_stance_time  r_pelvis_peak_drop_angle  r_pelvis_drop_excursion  r_ankle_df_peak_angle  r_ankle_eve_peak_angle  r_ankle_eve_percent_stance  r_ankle_eve_excursion  r_ankle_rot_peak_angle  r_ankle_rot_excursion  r_knee_flex_peak_angle  r_knee_add_peak_angle  r_knee_add_excursion  r_knee_abd_peak_angle  r_knee_abd_excursion  r_knee_rot_peak_angle  r_knee_rot_excursion  r_hip_ext_peak_angle  r_hip_add_peak_angle  r_hip_add_excursion  r_hip_rot_peak_angle  r_hip_rot_excursion  r_foot_prog_angle  r_foot_ang_at_hs  r_mhw_exc_from_to  r_ankle_eve_peak_vel  r_ankle_rot_peak_vel  r_knee_abd_peak_vel  r_knee_add_peak_vel  r_hip_abd_peak_vel  r_knee_rot_peak_vel  r_hip_rot_peak_vel  r_pronation_onset  r_pronation_offset  r_peak_hip_add_velocity  r_peak_pelvic_drop_velocity  r_vertical_oscillation injury_severity_code  injury_severity_value      injury_code injury2_code                                                                                                     injury_desc                                                                                     injury2_desc                   injury_name         injury2_name injured_joint_code injured_joint2_code injured_side_code injured_side2_code  has_no_injury  is_injured
606   100108_20100309T133425  100108  2010-03-09 13:34:25  20100309t133425.json  2.807481  60.0   185.5    85.0    male         NaN                      running, weights  recreational        50.0             full marathon          NaN           NaN           NaN     NaN       NaN  100108/20100309t133425.json      0.042051      83.720930         2.012028      0.416667       0.308333                  5.995375                 5.852726              22.074049               -6.517437                       0.360             -10.729952                2.842094              -8.972699              -46.520403              -7.081219              0.000000             -13.815016             -6.344395              -8.566803             12.047091             -0.146402             11.975451             9.975398             17.212862             5.183026           1.373895         18.865394          -7.110330           -183.437795            -83.296895          -160.256748            60.918244          -69.225608           186.401614          109.390360                 19                  64               161.946345                   -77.033913                     NaN      0.042051      83.720930         2.012028      0.408333       0.308333                 -3.325855                -6.900432              19.755734               -2.264956                       0.440             -12.049249                5.884140             -11.272438              -39.173694              -7.104680              0.302880             -13.088543             -5.648453             -10.640898             12.431500             -4.380011              9.764391            11.368217             14.384450             5.568149          -1.302453         25.131464          -6.828115           -172.390572           -130.330537          -154.669349            73.442576          -49.263263           147.208608          100.248389                 24                  68               142.323470                  -100.443060                     NaN        train_in_pain                    1.0             pain    no_injury                                               General sensation of discomfort  without specific injury details.                                                                    No injury has been diagnosed.                          pain            no injury              ankle           no_injury              left              right          False        True
630   100142_20100601T162620  100142  2010-06-01 16:26:20  20100601t162620.json  2.488109  28.0   160.0    66.6  female         NaN                               running  recreational         1.0  casual runner (no times)          NaN           NaN           NaN     NaN       NaN  100142/20100601t162620.json      0.063116      81.818182         1.824613      0.408333       0.325000                  5.957361                 6.122269              23.906772               -5.434591                       0.500              -9.177129               14.408651              -6.233558              -41.921830              -6.025453              1.630532             -13.329544             -5.556616             -10.779729             12.174507            -13.770220             13.351153             7.939837              7.041742             2.197268           1.042572         24.116153          -4.453870           -125.067406           -119.152713          -159.412797            83.368781          -77.120817           146.793548           71.191601                 23                  70               147.943869                  -136.136292                     NaN      0.063116      81.818182         1.824613      0.400000       0.333333                 -4.898714                -7.050662              25.528189               -8.172154                       0.485              -8.540721                4.843815              -6.750241              -45.435460              -3.518821              5.034879             -10.441323             -2.029900              -1.325134             11.133539            -16.403712             11.499532             8.341749              9.220011             0.000000           4.306736         20.712445          -9.636923           -107.479059            -80.940740           -83.383650            71.690244          -83.986678           139.030967           22.117682                 25                  66               141.671085                  -125.259045                     NaN     volume_intensity                    2.0             pain    no_injury                                               General sensation of discomfort  without specific injury details.                                                                    No injury has been diagnosed.                          pain            no injury               knee                knee             right               left          False        True
733   100184_20110808T104708  100184  2011-08-08 10:47:08  20110808t104708.json  2.264651  42.0   172.0    66.8  female        left                            not active  recreational         NaN  casual runner (no times)          NaN           NaN           NaN     NaN       NaN  100184/20110808t104708.json      0.147342      77.419355         1.755104      0.441667       0.333333                  5.188484                 4.572950              24.260414                2.585204                       0.480              -7.244479                9.775574              -5.904137              -52.504866              -9.357256              0.000000             -15.746725             -6.480025              -6.580086             12.638829             -1.392969              9.257984             7.358969              8.795253             3.644635          -1.758168         20.950387          -7.711025           -117.403107            -73.892715           -76.229088            58.267867          -66.517069           167.038299          108.762492                 23                  63               145.360801                   -85.397032                     NaN      0.147342      77.419355         1.755104      0.433333       0.341667                 -1.121661                -5.744114              21.934808                0.916277                       0.255              -5.757751                9.087390              -7.143389              -48.076130             -12.109437              0.000000             -23.586104            -11.447268             -11.576250             14.665140              1.057126              8.951332            10.118010             10.886481             5.210271          -7.107963         20.472932         -11.597880           -117.909946           -116.960747          -123.442047            68.231325          -86.340192           179.194105           98.748038                 16                  51               179.145649                  -100.911446                     NaN    missed_2_workouts                    3.0    low_back_pain         pain                                   Pain from mechanical stress, instability, or muscle imbalance in lower spine.                                General sensation of discomfort  without specific injury details.                 low back pain                 pain       lumbar_spine          hip_pelvis         bilateral               left          False        True
734   100185_20110809T162419  100185  2011-08-09 16:24:19  20110809t162419.json  2.473086  33.0   189.3    76.9    male        left      running, hiking, biking, weights  recreational         2.0  casual runner (no times)          NaN           NaN           NaN     NaN       NaN  100185/20110809t162419.json      0.100007      79.120879         1.875424      0.408333       0.350000                  4.819112                 7.360991              26.150124               -7.757815                       0.615             -16.269041                9.780755             -12.862591              -46.302636              -7.856850              0.000000             -14.231686             -6.300705              -8.333088             15.501903            -18.721635             12.403739            11.164309              5.615185             0.000000          -0.187676         22.463584          -3.418935           -254.292085           -125.029193          -134.833268            32.282072          -68.669278           159.566120            4.551536                 20                  80               137.411440                  -103.088527                     NaN      0.100007      79.120879         1.875424      0.425000       0.341667                 -3.918286                -5.568240              25.561187               -5.369913                       0.395             -11.113879                7.189619              -9.853482              -42.417143              -8.019092              0.000000             -12.775364             -4.524905             -14.465578             18.209048            -15.819320              8.294204             7.467494              9.600224             0.000000          -9.766320         26.414690          -2.518276           -166.065107           -101.023399          -131.421065            47.826233          -37.657550           185.369047           42.370823                 21                  65                95.658131                   -85.922004                     NaN    missed_2_workouts                    3.0             pain    no_injury                                               General sensation of discomfort  without specific injury details.                                                                    No injury has been diagnosed.                          pain            no injury               foot           no_injury         bilateral              right          False        True
764   100336_20111101T161543  100336  2011-11-01 16:15:43  20111101t161543.json  2.942184  42.0   177.7    74.6    male        left          triathlon, cycling, swimming  recreational        17.0  casual runner (no times)          NaN           NaN           NaN     NaN       NaN  100336/20111101t161543.json      0.139679      83.720930         2.108566      0.425000       0.291667                  5.023342                 2.883701              23.651616               -6.807293                       0.300             -11.431041                7.606210              -9.187637              -47.685378               0.749219              2.769633              -1.960225              0.000000              -3.594373             12.580438            -10.592272              6.515079             5.855205             15.067476             0.000000           5.355629         12.704136          -4.406226           -263.740973           -119.608813           -41.146748            50.760326          -48.035002           184.813601           52.065152                 14                  54               107.799211                   -42.920584                     NaN      0.139679      83.720930         2.108566      0.450000       0.266667                 -1.727349                -3.318810              24.042526               -9.521411                       0.325              -9.514510                3.855396              -9.336937              -42.701766              -1.213419              2.260352              -3.647832              0.000000              -2.925283              9.415716            -10.336901              5.536838             5.849005             11.358179             0.320488           6.465325         14.788170          -1.028986           -200.398415           -121.515638           -28.938248            38.672783          -37.224000           155.829996           29.396514                 17                  62               116.550390                   -53.459286                     NaN        train_in_pain                    1.0             pain    no_injury                                               General sensation of discomfort  without specific injury details.                                                                    No injury has been diagnosed.                          pain            no injury               knee           no_injury             right              right          False        True
787   100370_20120131T162449  100370  2012-01-31 16:24:49  20120131t162449.json  1.933503  57.0   170.0    73.3  female        left  race walking, yoga, pilates, weights   competitive         NaN  casual runner (no times)          NaN           NaN           NaN     NaN       NaN  100370/20120131t162449.json      0.131775      71.005917         1.633810      0.435000       0.410000                  0.854893                 4.444304              11.614692               -3.261798                       0.330              -6.315626                4.810272              -3.187720              -14.620546              -6.954383              0.171949             -11.734095             -4.436123              -5.513785             15.347035            -20.091745              8.579263             9.755558              5.923065             0.293571          -3.466481         32.335821          -2.928569            -94.436666            -64.887460           -58.401330            34.445601          -61.094648           171.465036           18.089914                 20                  90                95.792496                   -51.927176                     NaN      0.131775      71.005917         1.633810      0.440000       0.405000                 -5.092370                -4.053862              10.728285               -5.504774                       0.770              -5.568948                4.793393              -4.954749              -17.467318              -8.891303              1.518195             -14.225711             -3.930554             -16.357529             12.942906            -21.680130             14.614923            10.325742             18.726346             0.954443          -3.576824         33.729846          -3.876623            -66.803002            -82.981633           -69.428935            65.407182          -79.880168           165.161037           46.968541                 22                  89                89.894017                   -49.485024                     NaN     volume_intensity                    2.0   pate_pain_synd    no_injury  Pain around kneecap caused by poor tracking and mechanical friction of kneecap (patellofemoral pain syndrome).                                                                    No injury has been diagnosed.  patellofemoral pain syndrome            no injury               knee           no_injury              left              right          False        True
832   100502_20120531T155441  100502  2012-05-31 15:54:41  20120531t155441.json  1.924064  47.0   171.0    80.4  female       right    running, walking, biking, swimming  recreational         NaN  casual runner (no times)          NaN           NaN           NaN     NaN       NaN  100502/20120531t155441.json      0.074755      68.965517         1.673936      0.385000       0.485000                  1.110417                 6.281935              25.647770               -2.860323                       0.490              -8.062213                1.362384              -7.102671              -55.424685              -8.566063              0.000000             -16.908011             -8.281630               1.515945             17.641192              5.005709              9.240127            12.595954             15.444640             6.006230           2.663166         22.589822         -20.655301           -105.995116           -184.180085          -103.977363            75.570013          -49.439548           184.297686          154.729362                 21                  64               179.722085                  -108.271823                     NaN      0.074755      68.965517         1.673936      0.362500       0.510000                 -8.978601                -4.679691              26.816193               -8.224824                       0.390             -11.083428                2.681107              -5.954240              -58.735574              -3.941815              6.919416             -18.150281             -7.235173               4.109929             18.311182             -1.547146             18.918314             9.324929             14.096253             1.318609          -0.578848         20.818162          -5.519289           -127.081855           -106.035554           -91.550257            90.886224         -121.566247           181.146916          141.079560                 18                  54               163.298191                   -72.536689                     NaN        train_in_pain                    1.0        plan_fasc    achi_tend          Inflammation and pain of plantar fascia tissue on bottom of foot due to repetitive stress or overload.  Inflammation or irritation of Achilles tendon caused by repetitive loading or excessive strain.             plantar fasciitis  achilles tendonitis               foot               ankle             right              right          False        True

In [30]:
disc_vars = loader.get_discrete_variables()
disc_vars['Hz'].value_counts(normalize=True)

Hz
200    0.994484
120    0.005516
Name: proportion, dtype: float64

In [31]:
cleaned_data.columns.tolist()

['id',
 'sub_id',
 'datestring',
 'filename',
 'speed_r',
 'age',
 'Height',
 'Weight',
 'Gender',
 'DominantLeg',
 'Activities',
 'Level',
 'YrsRunning',
 'RaceDistance',
 'RaceTimeHrs',
 'RaceTimeMins',
 'RaceTimeSecs',
 'YrPR',
 'NumRaces',
 'session_file_path',
 'l_step_width',
 'l_stride_rate',
 'l_stride_length',
 'l_swing_time',
 'l_stance_time',
 'l_pelvis_peak_drop_angle',
 'l_pelvis_drop_excursion',
 'l_ankle_df_peak_angle',
 'l_ankle_eve_peak_angle',
 'l_ankle_eve_percent_stance',
 'l_ankle_eve_excursion',
 'l_ankle_rot_peak_angle',
 'l_ankle_rot_excursion',
 'l_knee_flex_peak_angle',
 'l_knee_add_peak_angle',
 'l_knee_add_excursion',
 'l_knee_abd_peak_angle',
 'l_knee_abd_excursion',
 'l_knee_rot_peak_angle',
 'l_knee_rot_excursion',
 'l_hip_ext_peak_angle',
 'l_hip_add_peak_angle',
 'l_hip_add_excursion',
 'l_hip_rot_peak_angle',
 'l_hip_rot_excursion',
 'l_foot_prog_angle',
 'l_foot_ang_at_hs',
 'l_mhw_exc_from_to',
 'l_ankle_eve_peak_vel',
 'l_ankle_rot_peak_vel',
 'l_knee_abd_peak_vel',
 'l_knee_add_peak_vel',
 'l_hip_abd_peak_vel',
 'l_knee_rot_peak_vel',
 'l_hip_rot_peak_vel',
 'l_pronation_onset',
 'l_pronation_offset',
 'l_peak_hip_add_velocity',
 'l_peak_pelvic_drop_velocity',
 'l_vertical_oscillation',
 'r_step_width',
 'r_stride_rate',
 'r_stride_length',
 'r_swing_time',
 'r_stance_time',
 'r_pelvis_peak_drop_angle',
 'r_pelvis_drop_excursion',
 'r_ankle_df_peak_angle',
 'r_ankle_eve_peak_angle',
 'r_ankle_eve_percent_stance',
 'r_ankle_eve_excursion',
 'r_ankle_rot_peak_angle',
 'r_ankle_rot_excursion',
 'r_knee_flex_peak_angle',
 'r_knee_add_peak_angle',
 'r_knee_add_excursion',
 'r_knee_abd_peak_angle',
 'r_knee_abd_excursion',
 'r_knee_rot_peak_angle',
 'r_knee_rot_excursion',
 'r_hip_ext_peak_angle',
 'r_hip_add_peak_angle',
 'r_hip_add_excursion',
 'r_hip_rot_peak_angle',
 'r_hip_rot_excursion',
 'r_foot_prog_angle',
 'r_foot_ang_at_hs',
 'r_mhw_exc_from_to',
 'r_ankle_eve_peak_vel',
 'r_ankle_rot_peak_vel',
 'r_knee_abd_peak_vel',
 'r_knee_add_peak_vel',
 'r_hip_abd_peak_vel',
 'r_knee_rot_peak_vel',
 'r_hip_rot_peak_vel',
 'r_pronation_onset',
 'r_pronation_offset',
 'r_peak_hip_add_velocity',
 'r_peak_pelvic_drop_velocity',
 'r_vertical_oscillation',
 'injury_severity_code',
 'injury_severity_value',
 'injury_code',
 'injury2_code',
 'injury_desc',
 'injury2_desc',
 'injury_name',
 'injury2_name',
 'injured_joint_code',
 'injured_joint2_code',
 'injured_side_code',
 'injured_side2_code',
 'has_no_injury',
 'is_injured']

In [32]:
injured_not_severity = cleaned_data[cleaned_data["injury_code"].isin(["no_injury"]) & ~(cleaned_data["injury_severity_value"] == 0)][["injury_code", "injury_severity_code"]]
not_injured_severity = cleaned_data[~cleaned_data["injury_code"].isin(["no_injury"]) & (cleaned_data["injury_severity_value"] == 0)][["injury_code", "injury_severity_code"]]

display(injured_not_severity)
display(not_injured_severity)

total_diff = len(injured_not_severity) + len(not_injured_severity)
print(f"Total difference: {total_diff}")

print("Percentage miss represented in the dataset: ", (total_diff / len(cleaned_data)) * 100)

     injury_code injury_severity_code
74     no_injury     volume_intensity
78     no_injury     volume_intensity
142    no_injury        train_in_pain
202    no_injury     volume_intensity
227    no_injury    missed_2_workouts
...          ...                  ...
1331   no_injury                  NaN
1332   no_injury                  NaN
1333   no_injury                  NaN
1334   no_injury                  NaN
1335   no_injury                  NaN

[87 rows x 2 columns]

         injury_code injury_severity_code
601             pain            no_injury
680   fibu_stre_frac            no_injury
743             pain            no_injury
748        achi_tend            no_injury
751             pain            no_injury
...              ...                  ...
1605            pain            no_injury
1606            pain            no_injury
1679            chon            no_injury
1680            chon            no_injury
1793  calf_musc_stra            no_injury

[81 rows x 2 columns]

Total difference: 168
Percentage miss represented in the dataset:  9.170305676855897

In [33]:
# Distribution of injured vs uninjured in full dataset:
cleaned_data["is_injured"].value_counts(normalize=True)

is_injured
True     0.637009
False    0.362991
Name: proportion, dtype: float64

Test equality between computed descritptive variables and the provided data

In [34]:
discrete_data = loader.get_discrete_variables()
display(discrete_data.info(verbose=True))

session_data = loader.get_session_data_full_cleaned()
display(session_data.info(verbose=True))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1813 entries, 0 to 1812
Data columns (total 84 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   ID                              1813 non-null   object
 1   Speed_Output                    1813 non-null   float64
 2   Label                           1813 non-null   object
 3   Hz                              1813 non-null   int64
 4   Step_Width_Left                 1813 non-null   float64
 5   Step_Width_Right                1813 non-null   float64
 6   Stride_Rate_Left                1813 non-null   float64
 7   Stride_Rate_Right               1813 non-null   float64
 8   Stride_Length_Left              1813 non-null   float64
 9   Stride_Length_Right             1813 non-null   float64
 10  Swing_Time_Left                 1813 non-null   float64
 11  Swing_Time_Right                1813 non-null   float64
 12  Stance_Time_Left                1813 non-null   float64
 13  Stance_Time_Right               1813 non-null   float64
 14  Pelvis_Peak_Drop_Angle_Left     1813 non-null   float64
 15  Pelvis_Peak_Drop_Angle_Right    1813 non-null   float64
 16  Pelvis_Drop_Excursion_Left      1813 non-null   float64
 17  Pelvis_Drop_Excursion_Right     1813 non-null   float64
 18  Ankle_DF_Peak_Angle_Left        1813 non-null   float64
 19  Ankle_DF_Peak_Angle_Right       1813 non-null   float64
 20  Ankle_Eve_Peak_Angle_Left       1813 non-null   float64
 21  Ankle_Eve_Peak_Angle_Right      1813 non-null   float64
 22  Ankle_Eve_Percent_Stance_Left   1813 non-null   float64
 23  Ankle_Eve_Percent_Stance_Right  1813 non-null   float64
 24  Ankle_Eve_Excursion_Left        1813 non-null   float64
 25  Ankle_Eve_Excursion_Right       1813 non-null   float64
 26  Ankle_Rot_Peak_Angle_Left       1813 non-null   float64
 27  Ankle_Rot_Peak_Angle_Right      1813 non-null   float64
 28  Ankle_Rot_Excursion_Left        1813 non-null   float64
 29  Ankle_Rot_Excursion_Right       1813 non-null   float64
 30  Knee_Flex_Peak_Angle_Left       1813 non-null   float64
 31  Knee_Flex_Peak_Angle_Right      1813 non-null   float64
 32  Knee_Add_Peak_Angle_Left        1813 non-null   float64
 33  Knee_Add_Peak_Angle_Right       1813 non-null   float64
 34  Knee_Add_Excursion_Left         1813 non-null   float64
 35  Knee_Add_Excursion_Right        1813 non-null   float64
 36  Knee_Abd_Peak_Angle_Left        1813 non-null   float64
 37  Knee_Abd_Peak_Angle_Right       1813 non-null   float64
 38  Knee_Abd_Excursion_Left         1813 non-null   float64
 39  Knee_Abd_Excursion_Right        1813 non-null   float64
 40  Knee_Rot_Peak_Angle_Left        1813 non-null   float64
 41  Knee_Rot_Peak_Angle_Right       1813 non-null   float64
 42  Knee_Rot_Excursion_Left         1813 non-null   float64
 43  Knee_Rot_Excursion_Right        1813 non-null   float64
 44  Hip_Ext_Peak_Angle_Left         1813 non-null   float64
 45  Hip_Ext_Peak_Angle_Right        1813 non-null   float64
 46  Hip_Add_Peak_Angle_Left         1813 non-null   float64
 47  Hip_Add_Peak_Angle_Right        1813 non-null   float64
 48  Hip_Add_Excursion_Left          1813 non-null   float64
 49  Hip_Add_Excursion_Right         1813 non-null   float64
 50  Hip_Rot_Peak_Angle_Left         1813 non-null   float64
 51  Hip_Rot_Peak_Angle_Right        1813 non-null   float64
 52  Hip_Rot_Excursion_Left          1813 non-null   float64
 53  Hip_Rot_Excursion_Right         1813 non-null   float64
 54  Foot_Prog_Angle_Left            1813 non-null   float64
 55  Foot_Prog_Angle_Right           1813 non-null   float64
 56  Foot_Ang_At_HS_Left             1813 non-null   float64
 57  Foot_Ang_At_HS_Right            1813 non-null   float64
 58  MHW_Exc_From_TO_Left            1813 non-null   float64
 59  MHW_Exc_From_TO_Right           1813 non-null   float64
 60  Ankle_Eve_Peak_Vel_Left         1813 non-null   float64
 61  Ankle_Eve_Peak_Vel_Right        1813 non-null   float64
 62  Ankle_Rot_Peak_Vel_Left         1813 non-null   float64
 63  Ankle_Rot_Peak_Vel_Right        1813 non-null   float64
 64  Knee_Abd_Peak_Vel_Left          1813 non-null   float64
 65  Knee_Abd_Peak_Vel_Right         1813 non-null   float64
 66  Knee_Add_Peak_Vel_Left          1813 non-null   float64
 67  Knee_Add_Peak_Vel_Right         1813 non-null   float64
 68  Hip_Abd_Peak_Vel_Left           1813 non-null   float64
 69  Hip_Abd_Peak_Vel_Right          1813 non-null   float64
 70  Knee_Rot_Peak_Vel_Left          1813 non-null   float64
 71  Knee_Rot_Peak_Vel_Right         1813 non-null   float64
 72  Hip_Rot_Peak_Vel_Left           1813 non-null   float64
 73  Hip_Rot_Peak_Vel_Right          1813 non-null   float64
 74  Pronation_Onset_Left            1813 non-null   int64
 75  Pronation_Onset_Right           1813 non-null   int64
 76  Supination_Timing_Left          1813 non-null   int64
 77  Supination_Timing_Right         1813 non-null   int64
 78  Hip_Add_Peak_Vel_Left           1813 non-null   float64
 79  Hip_Add_Peak_Vel_Right          1813 non-null   float64
 80  Pelvic_Drop_Peak_Vel_Left       1813 non-null   float64
 81  Pelvic_Drop_Peak_Vel_Right      1813 non-null   float64
 82  Vertical_Oscillation_Left       1801 non-null   float64
 83  Vertical_Oscillation_Right      1801 non-null   float64
dtypes: float64(77), int64(5), object(2)
memory usage: 1.2+ MB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1832 entries, 0 to 1831
Data columns (total 114 columns):
 #    Column                       Dtype
---   ------                       -----
 0    id                           object
 1    sub_id                       int64
 2    datestring                   object
 3    filename                     object
 4    speed_r                      float64
 5    age                          float64
 6    Height                       float64
 7    Weight                       float64
 8    Gender                       object
 9    DominantLeg                  object
 10   Activities                   object
 11   Level                        object
 12   YrsRunning                   float64
 13   RaceDistance                 object
 14   RaceTimeHrs                  float64
 15   RaceTimeMins                 float64
 16   RaceTimeSecs                 float64
 17   YrPR                         float64
 18   NumRaces                     float64
 19   session_file_path            object
 20   l_step_width                 float64
 21   l_stride_rate                float64
 22   l_stride_length              float64
 23   l_swing_time                 float64
 24   l_stance_time                float64
 25   l_pelvis_peak_drop_angle     float64
 26   l_pelvis_drop_excursion      float64
 27   l_ankle_df_peak_angle        float64
 28   l_ankle_eve_peak_angle       float64
 29   l_ankle_eve_percent_stance   float64
 30   l_ankle_eve_excursion        float64
 31   l_ankle_rot_peak_angle       float64
 32   l_ankle_rot_excursion        float64
 33   l_knee_flex_peak_angle       float64
 34   l_knee_add_peak_angle        float64
 35   l_knee_add_excursion         float64
 36   l_knee_abd_peak_angle        float64
 37   l_knee_abd_excursion         float64
 38   l_knee_rot_peak_angle        float64
 39   l_knee_rot_excursion         float64
 40   l_hip_ext_peak_angle         float64
 41   l_hip_add_peak_angle         float64
 42   l_hip_add_excursion          float64
 43   l_hip_rot_peak_angle         float64
 44   l_hip_rot_excursion          float64
 45   l_foot_prog_angle            float64
 46   l_foot_ang_at_hs             float64
 47   l_mhw_exc_from_to            float64
 48   l_ankle_eve_peak_vel         float64
 49   l_ankle_rot_peak_vel         float64
 50   l_knee_abd_peak_vel          float64
 51   l_knee_add_peak_vel          float64
 52   l_hip_abd_peak_vel           float64
 53   l_knee_rot_peak_vel          float64
 54   l_hip_rot_peak_vel           float64
 55   l_pronation_onset            int64
 56   l_pronation_offset           int64
 57   l_peak_hip_add_velocity      float64
 58   l_peak_pelvic_drop_velocity  float64
 59   l_vertical_oscillation       float64
 60   r_step_width                 float64
 61   r_stride_rate                float64
 62   r_stride_length              float64
 63   r_swing_time                 float64
 64   r_stance_time                float64
 65   r_pelvis_peak_drop_angle     float64
 66   r_pelvis_drop_excursion      float64
 67   r_ankle_df_peak_angle        float64
 68   r_ankle_eve_peak_angle       float64
 69   r_ankle_eve_percent_stance   float64
 70   r_ankle_eve_excursion        float64
 71   r_ankle_rot_peak_angle       float64
 72   r_ankle_rot_excursion        float64
 73   r_knee_flex_peak_angle       float64
 74   r_knee_add_peak_angle        float64
 75   r_knee_add_excursion         float64
 76   r_knee_abd_peak_angle        float64
 77   r_knee_abd_excursion         float64
 78   r_knee_rot_peak_angle        float64
 79   r_knee_rot_excursion         float64
 80   r_hip_ext_peak_angle         float64
 81   r_hip_add_peak_angle         float64
 82   r_hip_add_excursion          float64
 83   r_hip_rot_peak_angle         float64
 84   r_hip_rot_excursion          float64
 85   r_foot_prog_angle            float64
 86   r_foot_ang_at_hs             float64
 87   r_mhw_exc_from_to            float64
 88   r_ankle_eve_peak_vel         float64
 89   r_ankle_rot_peak_vel         float64
 90   r_knee_abd_peak_vel          float64
 91   r_knee_add_peak_vel          float64
 92   r_hip_abd_peak_vel           float64
 93   r_knee_rot_peak_vel          float64
 94   r_hip_rot_peak_vel           float64
 95   r_pronation_onset            int64
 96   r_pronation_offset           int64
 97   r_peak_hip_add_velocity      float64
 98   r_peak_pelvic_drop_velocity  float64
 99   r_vertical_oscillation       float64
 100  injury_severity_code         object
 101  injury_severity_value        float64
 102  injury_code                  object
 103  injury2_code                 object
 104  injury_desc                  object
 105  injury2_desc                 object
 106  injury_name                  object
 107  injury2_name                 object
 108  injured_joint_code           object
 109  injured_joint2_code          object
 110  injured_side_code            object
 111  injured_side2_code           object
 112  has_no_injury                bool
 113  is_injured                   bool
dtypes: bool(2), float64(87), int64(5), object(20)
memory usage: 1.6+ MB

None

In [35]:
# Compare raw discrete variables vs session metadata
d_raw = loader.get_discrete_variables()
s_raw = loader.get_session_data_full_cleaned()

In [36]:
# Manual mapping: discrete_variables.csv -> session_data_full_cleaned.csv
DISCRETE_TO_SESSION_COLUMN_MAP = {
    # identifiers / speed
    "Speed_Output": "speed_r",
    "ID": "id",
    # left side
    "Step_Width_Left": "l_step_width",
    "Stride_Rate_Left": "l_stride_rate",
    "Stride_Length_Left": "l_stride_length",
    "Swing_Time_Left": "l_swing_time",
    "Stance_Time_Left": "l_stance_time",
    "Pelvis_Peak_Drop_Angle_Left": "l_pelvis_peak_drop_angle",
    "Pelvis_Drop_Excursion_Left": "l_pelvis_drop_excursion",
    "Ankle_DF_Peak_Angle_Left": "l_ankle_df_peak_angle",
    "Ankle_Eve_Peak_Angle_Left": "l_ankle_eve_peak_angle",
    "Ankle_Eve_Percent_Stance_Left": "l_ankle_eve_percent_stance",
    "Ankle_Eve_Excursion_Left": "l_ankle_eve_excursion",
    "Ankle_Rot_Peak_Angle_Left": "l_ankle_rot_peak_angle",
    "Ankle_Rot_Excursion_Left": "l_ankle_rot_excursion",
    "Knee_Flex_Peak_Angle_Left": "l_knee_flex_peak_angle",
    "Knee_Add_Peak_Angle_Left": "l_knee_add_peak_angle",
    "Knee_Add_Excursion_Left": "l_knee_add_excursion",
    "Knee_Abd_Peak_Angle_Left": "l_knee_abd_peak_angle",
    "Knee_Abd_Excursion_Left": "l_knee_abd_excursion",
    "Knee_Rot_Peak_Angle_Left": "l_knee_rot_peak_angle",
    "Knee_Rot_Excursion_Left": "l_knee_rot_excursion",
    "Hip_Ext_Peak_Angle_Left": "l_hip_ext_peak_angle",
    "Hip_Add_Peak_Angle_Left": "l_hip_add_peak_angle",
    "Hip_Add_Excursion_Left": "l_hip_add_excursion",
    "Hip_Rot_Peak_Angle_Left": "l_hip_rot_peak_angle",
    "Hip_Rot_Excursion_Left": "l_hip_rot_excursion",
    "Foot_Prog_Angle_Left": "l_foot_prog_angle",
    "Foot_Ang_At_HS_Left": "l_foot_ang_at_hs",
    "MHW_Exc_From_TO_Left": "l_mhw_exc_from_to",
    "Ankle_Eve_Peak_Vel_Left": "l_ankle_eve_peak_vel",
    "Ankle_Rot_Peak_Vel_Left": "l_ankle_rot_peak_vel",
    "Knee_Abd_Peak_Vel_Left": "l_knee_abd_peak_vel",
    "Knee_Add_Peak_Vel_Left": "l_knee_add_peak_vel",
    "Hip_Abd_Peak_Vel_Left": "l_hip_abd_peak_vel",
    "Knee_Rot_Peak_Vel_Left": "l_knee_rot_peak_vel",
    "Hip_Rot_Peak_Vel_Left": "l_hip_rot_peak_vel",
    "Pronation_Onset_Left": "l_pronation_onset",
    "Supination_Timing_Left": "l_pronation_offset",
    "Hip_Add_Peak_Vel_Left": "l_peak_hip_add_velocity",
    "Pelvic_Drop_Peak_Vel_Left": "l_peak_pelvic_drop_velocity",
    "Vertical_Oscillation_Left": "l_vertical_oscillation",

    # right side
    "Step_Width_Right": "r_step_width",
    "Stride_Rate_Right": "r_stride_rate",
    "Stride_Length_Right": "r_stride_length",
    "Swing_Time_Right": "r_swing_time",
    "Stance_Time_Right": "r_stance_time",
    "Pelvis_Peak_Drop_Angle_Right": "r_pelvis_peak_drop_angle",
    "Pelvis_Drop_Excursion_Right": "r_pelvis_drop_excursion",
    "Ankle_DF_Peak_Angle_Right": "r_ankle_df_peak_angle",
    "Ankle_Eve_Peak_Angle_Right": "r_ankle_eve_peak_angle",
    "Ankle_Eve_Percent_Stance_Right": "r_ankle_eve_percent_stance",
    "Ankle_Eve_Excursion_Right": "r_ankle_eve_excursion",
    "Ankle_Rot_Peak_Angle_Right": "r_ankle_rot_peak_angle",
    "Ankle_Rot_Excursion_Right": "r_ankle_rot_excursion",
    "Knee_Flex_Peak_Angle_Right": "r_knee_flex_peak_angle",
    "Knee_Add_Peak_Angle_Right": "r_knee_add_peak_angle",
    "Knee_Add_Excursion_Right": "r_knee_add_excursion",
    "Knee_Abd_Peak_Angle_Right": "r_knee_abd_peak_angle",
    "Knee_Abd_Excursion_Right": "r_knee_abd_excursion",
    "Knee_Rot_Peak_Angle_Right": "r_knee_rot_peak_angle",
    "Knee_Rot_Excursion_Right": "r_knee_rot_excursion",
    "Hip_Ext_Peak_Angle_Right": "r_hip_ext_peak_angle",
    "Hip_Add_Peak_Angle_Right": "r_hip_add_peak_angle",
    "Hip_Add_Excursion_Right": "r_hip_add_excursion",
    "Hip_Rot_Peak_Angle_Right": "r_hip_rot_peak_angle",
    "Hip_Rot_Excursion_Right": "r_hip_rot_excursion",
    "Foot_Prog_Angle_Right": "r_foot_prog_angle",
    "Foot_Ang_At_HS_Right": "r_foot_ang_at_hs",
    "MHW_Exc_From_TO_Right": "r_mhw_exc_from_to",
    "Ankle_Eve_Peak_Vel_Right": "r_ankle_eve_peak_vel",
    "Ankle_Rot_Peak_Vel_Right": "r_ankle_rot_peak_vel",
    "Knee_Abd_Peak_Vel_Right": "r_knee_abd_peak_vel",
    "Knee_Add_Peak_Vel_Right": "r_knee_add_peak_vel",
    "Hip_Abd_Peak_Vel_Right": "r_hip_abd_peak_vel",
    "Knee_Rot_Peak_Vel_Right": "r_knee_rot_peak_vel",
    "Hip_Rot_Peak_Vel_Right": "r_hip_rot_peak_vel",
    "Pronation_Onset_Right": "r_pronation_onset",
    "Supination_Timing_Right": "r_pronation_offset",
    "Hip_Add_Peak_Vel_Right": "r_peak_hip_add_velocity",
    "Pelvic_Drop_Peak_Vel_Right": "r_peak_pelvic_drop_velocity",
    "Vertical_Oscillation_Right": "r_vertical_oscillation",
}



d_compare = d_raw.rename(columns=DISCRETE_TO_SESSION_COLUMN_MAP).set_index("id")
s_compare = s_raw.set_index("id")
display(d_compare.head())
display(s_compare.head())

,speed_r,Label,Hz,l_step_width,r_step_width,l_stride_rate,r_stride_rate,l_stride_length,r_stride_length,l_swing_time,...,l_pronation_onset,r_pronation_onset,l_pronation_offset,r_pronation_offset,l_peak_hip_add_velocity,r_peak_hip_add_velocity,l_peak_pelvic_drop_velocity,r_peak_pelvic_drop_velocity,l_vertical_oscillation,r_vertical_oscillation
id,,,,,,,,,,,,,,,,,,,,,
100001_20110531T161051,2.489233,run,200,0.123419,0.123419,78.947368,78.947368,1.891817,1.891817,0.4350,...,19,18,61,64,85.020264,87.908897,-82.090017,-57.417845,96.433793,92.586134
100002_20110601T140505,2.722687,run,200,0.032922,0.032922,81.632653,81.632653,2.001175,2.001175,0.4450,...,6,9,52,29,128.876737,123.900795,-57.724685,-60.462411,86.521432,94.945518
100003_20110601T095930,2.949904,run,200,0.097273,0.097273,78.947368,78.947368,2.241927,2.241927,0.4475,...,15,12,60,46,164.445008,161.075363,-82.171073,-95.302664,82.680986,76.611379
100004_20110203T120721,2.688014,run,200,0.011401,0.011401,82.191781,82.191781,1.962250,1.962250,0.4400,...,12,11,44,52,114.693386,123.606287,-63.319119,-49.646132,92.593339,83.273183
100004_20140929T102035,2.928598,run,200,0.029021,0.029021,83.333333,82.758621,2.108590,2.123233,0.4200,...,13,10,43,47,132.372005,129.000180,-32.717949,-52.004473,87.481400,75.091789

,sub_id,datestring,filename,speed_r,age,Height,Weight,Gender,DominantLeg,Activities,...,injury_desc,injury2_desc,injury_name,injury2_name,injured_joint_code,injured_joint2_code,injured_side_code,injured_side2_code,has_no_injury,is_injured
id,,,,,,,,,,,,,,,,,,,,,
100433_20101005T132240,100433,2010-10-05 13:22:40,20101005t132240.json,1.610861,53.0,NaN,NaN,NaN,NaN,"walking, horseback riding, strength training",...,General sensation of discomfort without speci...,No injury has been diagnosed.,pain,no injury,knee,no_injury,right,right,False,True
100434_20101117T132240,100434,2010-11-17 13:22:40,20101117t132240.json,2.237294,51.0,NaN,NaN,female,NaN,"running, swimming",...,Breakdown and gradual loss of spinal disc cush...,No injury has been diagnosed.,disc degeneration,no injury,lumbar_spine,no_injury,bilateral,right,False,True
100537_20120703T102550,100537,2012-07-03 10:25:50,20120703t102550.json,2.127441,NaN,173.1,67.6,female,right,"hiking, power walking, pilates",...,General sensation of discomfort without speci...,No injury has been diagnosed.,pain,no injury,hip_pelvis,no_injury,right,right,False,True
100560_20120717T103748,100560,2012-07-17 10:37:48,20120717t103748.json,2.657365,33.0,179.3,83.0,female,right,yoga,...,No injury has been diagnosed.,No injury has been diagnosed.,no injury,no injury,no_injury,no_injury,right,right,True,False
101481_20120717T105021,101481,2012-07-17 10:50:21,20120717t105021.json,2.625088,32.0,176.3,58.6,female,NaN,NaN,...,No injury has been diagnosed.,No injury has been diagnosed.,no injury,no injury,no_injury,no_injury,no_injury,no_injury,True,False

In [37]:
d_ids = set(d_compare.index.astype(str))
s_ids = set(s_compare.index.astype(str))

print(f"Discrete rows (mapped): {len(d_compare):,}, unique ids: {len(d_ids):,}")
print(f"Session rows (mapped):  {len(s_compare):,}, unique ids: {len(s_ids):,}")
print("")

# ID coverage comparison
missing_in_session = sorted(list(d_ids - s_ids))
missing_in_discrete = sorted(list(s_ids - d_ids))
print(f"IDs in discrete (mapped) but not in session: {len(missing_in_session)}")
print(f"IDs in session (mapped) but not in discrete: {len(missing_in_discrete)}")
if missing_in_session[:5]:
    print("Sample (discrete-only):", missing_in_session[:5])
if missing_in_discrete[:5]:
    print("Sample (session-only): ", missing_in_discrete[:5])

Discrete rows (mapped): 1,813, unique ids: 1,813
Session rows (mapped):  1,832, unique ids: 1,832

IDs in discrete (mapped) but not in session: 1
IDs in session (mapped) but not in discrete: 20
Sample (discrete-only): ['200375_20140502T074159']
Sample (session-only):  ['100218_20110921T141851', '100313_20110209T125643', '100319_20110408T122343', '100390_20120315T133207', '101146_20140707T124250']

In [38]:
ids_intersection = sorted(list(d_ids & s_ids))
common_lower = set(d_compare.columns).intersection(s_compare.columns)

if not ids_intersection:
    print("No overlapping IDs to compare.")
else:
    # Index expected: 'id'
    d_indexed = d_compare.loc[ids_intersection]
    s_indexed = s_compare.loc[ids_intersection]

    comparison_results = []
    mismatch_examples = {}

    for col_lower in sorted(common_lower):
        d_vals = d_indexed[col_lower]
        s_vals = s_indexed[col_lower]

        # Attempt numeric comparison if possible
        d_num = pd.to_numeric(d_vals, errors="coerce")
        s_num = pd.to_numeric(s_vals, errors="coerce")
        is_numeric = (d_num.notna() | s_num.notna()).mean() >= 0.5

        if is_numeric:
            equal = np.isclose(d_num.values, s_num.values, rtol=1e-5, atol=1e-5, equal_nan=True)
        else:
            # Compare as normalized strings, treating NA==NA as equal
            d_str = d_vals.astype("string").str.strip().str.lower()
            s_str = s_vals.astype("string").str.strip().str.lower()
            both_na = d_str.isna() & s_str.isna()
            equal = (d_str == s_str) | both_na
            equal = equal.values

        n_total = len(equal)
        n_match = int(equal.sum())
        n_mismatch = n_total - n_match
        match_rate = n_match / n_total if n_total else np.nan

        # Collect up to N mismatch examples
        N = 10
        if n_mismatch > 0:
            mismatch_idx = np.where(~equal)[0][:N]
            mismatch_examples[col_lower] = [
                {
                    "id": ids_intersection[i],
                    f"discrete.{col_lower}": d_vals.iloc[i],
                    f"session.{col_lower}": s_vals.iloc[i],
                }
                for i in mismatch_idx
            ]

        comparison_results.append({
            "column": col_lower,
            "dtype_discrete": str(d_vals.dtype),
            "dtype_session": str(s_vals.dtype),
            "rows_compared": n_total,
            "matches": n_match,
            "mismatches": n_mismatch,
            "match_rate": round(match_rate, 6),
        })

    comparison_df = pd.DataFrame(comparison_results).sort_values(["match_rate", "mismatches"], ascending=[True, False])

    with pd.option_context("display.max_rows", None):
        display(comparison_df)

    if mismatch_examples:
        print(f"\nExample mismatches (up to {N} per column):")
        for col, rows in mismatch_examples.items():
            print(f"- {col}:")
            for row in rows:
                print("  ", row)

,column,dtype_discrete,dtype_session,rows_compared,matches,mismatches,match_rate
80,speed_r,float64,float64,1812,1778,34,0.981236
0,l_ankle_df_peak_angle,float64,float64,1812,1812,0,1.000000
1,l_ankle_eve_excursion,float64,float64,1812,1812,0,1.000000
2,l_ankle_eve_peak_angle,float64,float64,1812,1812,0,1.000000
3,l_ankle_eve_peak_vel,float64,float64,1812,1812,0,1.000000
4,l_ankle_eve_percent_stance,float64,float64,1812,1812,0,1.000000
5,l_ankle_rot_excursion,float64,float64,1812,1812,0,1.000000
6,l_ankle_rot_peak_angle,float64,float64,1812,1812,0,1.000000
7,l_ankle_rot_peak_vel,float64,float64,1812,1812,0,1.000000
8,l_foot_ang_at_hs,float64,float64,1812,1812,0,1.000000
9,l_foot_prog_angle,float64,float64,1812,1812,0,1.000000
10,l_hip_abd_peak_vel,float64,float64,1812,1812,0,1.000000
11,l_hip_add_excursion,float64,float64,1812,1812,0,1.000000
12,l_hip_add_peak_angle,float64,float64,1812,1812,0,1.000000
13,l_hip_ext_peak_angle,float64,float64,1812,1812,0,1.000000
14,l_hip_rot_excursion,float64,float64,1812,1812,0,1.000000
15,l_hip_rot_peak_angle,float64,float64,1812,1812,0,1.000000
16,l_hip_rot_peak_vel,float64,float64,1812,1812,0,1.000000
17,l_knee_abd_excursion,float64,float64,1812,1812,0,1.000000
18,l_knee_abd_peak_angle,float64,float64,1812,1812,0,1.000000
19,l_knee_abd_peak_vel,float64,float64,1812,1812,0,1.000000
20,l_knee_add_excursion,float64,float64,1812,1812,0,1.000000
21,l_knee_add_peak_angle,float64,float64,1812,1812,0,1.000000
22,l_knee_add_peak_vel,float64,float64,1812,1812,0,1.000000
23,l_knee_flex_peak_angle,float64,float64,1812,1812,0,1.000000
24,l_knee_rot_excursion,float64,float64,1812,1812,0,1.000000
25,l_knee_rot_peak_angle,float64,float64,1812,1812,0,1.000000
26,l_knee_rot_peak_vel,float64,float64,1812,1812,0,1.000000
27,l_mhw_exc_from_to,float64,float64,1812,1812,0,1.000000
28,l_peak_hip_add_velocity,float64,float64,1812,1812,0,1.000000
29,l_peak_pelvic_drop_velocity,float64,float64,1812,1812,0,1.000000
30,l_pelvis_drop_excursion,float64,float64,1812,1812,0,1.000000
31,l_pelvis_peak_drop_angle,float64,float64,1812,1812,0,1.000000
32,l_pronation_offset,int64,int64,1812,1812,0,1.000000
33,l_pronation_onset,int64,int64,1812,1812,0,1.000000
34,l_stance_time,float64,float64,1812,1812,0,1.000000
35,l_step_width,float64,float64,1812,1812,0,1.000000
36,l_stride_length,float64,float64,1812,1812,0,1.000000
37,l_stride_rate,float64,float64,1812,1812,0,1.000000
38,l_swing_time,float64,float64,1812,1812,0,1.000000
39,l_vertical_oscillation,float64,float64,1812,1812,0,1.000000
40,r_ankle_df_peak_angle,float64,float64,1812,1812,0,1.000000
41,r_ankle_eve_excursion,float64,float64,1812,1812,0,1.000000
42,r_ankle_eve_peak_angle,float64,float64,1812,1812,0,1.000000
43,r_ankle_eve_peak_vel,float64,float64,1812,1812,0,1.000000
44,r_ankle_eve_percent_stance,float64,float64,1812,1812,0,1.000000
45,r_ankle_rot_excursion,float64,float64,1812,1812,0,1.000000
46,r_ankle_rot_peak_angle,float64,float64,1812,1812,0,1.000000
47,r_ankle_rot_peak_vel,float64,float64,1812,1812,0,1.000000
48,r_foot_ang_at_hs,float64,float64,1812,1812,0,1.000000
49,r_foot_prog_angle,float64,float64,1812,1812,0,1.000000
50,r_hip_abd_peak_vel,float64,float64,1812,1812,0,1.000000
51,r_hip_add_excursion,float64,float64,1812,1812,0,1.000000
52,r_hip_add_peak_angle,float64,float64,1812,1812,0,1.000000
53,r_hip_ext_peak_angle,float64,float64,1812,1812,0,1.000000
54,r_hip_rot_excursion,float64,float64,1812,1812,0,1.000000
55,r_hip_rot_peak_angle,float64,float64,1812,1812,0,1.000000
56,r_hip_rot_peak_vel,float64,float64,1812,1812,0,1.000000
57,r_knee_abd_excursion,float64,float64,1812,1812,0,1.000000
58,r_knee_abd_peak_angle,float64,float64,1812,1812,0,1.000000
59,r_knee_abd_peak_vel,float64,float64,1812,1812,0,1.000000
60,r_knee_add_excursion,float64,float64,1812,1812,0,1.000000
61,r_knee_add_peak_angle,float64,float64,1812,1812,0,1.000000
62,r_knee_add_peak_vel,float64,float64,1812,1812,0,1.000000
63,r_knee_flex_peak_angle,float64,float64,1812,1812,0,1.000000
64,r_knee_rot_excursion,float64,float64,1812,1812,0,1.000000
65,r_knee_rot_peak_angle,float64,float64,1812,1812,0,1.000000
66,r_knee_rot_peak_vel,float64,float64,1812,1812,0,1.000000
67,r_mhw_exc_from_to,float64,float64,1812,1812,0,1.000000
68,r_peak_hip_add_velocity,float64,float64,1812,1812,0,1.000000
69,r_peak_pelvic_drop_velocity,float64,float64,1812,1812,0,1.000000
70,r_pelvis_drop_excursion,float64,float64,1812,1812,0,1.000000
71,r_pelvis_peak_drop_angle,float64,float64,1812,1812,0,1.000000
72,r_pronation_offset,int64,int64,1812,1812,0,1.000000
73,r_pronation_onset,int64,int64,1812,1812,0,1.000000
74,r_stance_time,float64,float64,1812,1812,0,1.000000
75,r_step_width,float64,float64,1812,1812,0,1.000000
76,r_stride_length,float64,float64,1812,1812,0,1.000000
77,r_stride_rate,float64,float64,1812,1812,0,1.000000
78,r_swing_time,float64,float64,1812,1812,0,1.000000
79,r_vertical_oscillation,float64,float64,1812,1812,0,1.000000

Example mismatches (up to 10 per column):
- speed_r:
   {'id': '100021_20110404T121612', 'discrete.speed_r': np.float64(2.47954905222518), 'session.speed_r': np.float64(2.4796)}
   {'id': '100024_20110419T164319', 'discrete.speed_r': np.float64(2.02836135827108), 'session.speed_r': np.float64(2.02816237897558)}
   {'id': '100032_20110524T121658', 'discrete.speed_r': np.float64(2.93882802680827), 'session.speed_r': np.float64(2.93029883737747)}
   {'id': '100048_20110615T114931', 'discrete.speed_r': np.float64(2.27695630629851), 'session.speed_r': np.float64(2.27520107194728)}
   {'id': '100052_20110616T114739', 'discrete.speed_r': np.float64(2.70424608901999), 'session.speed_r': np.float64(2.7043)}
   {'id': '100067_20110705T163155', 'discrete.speed_r': np.float64(2.24973768027712), 'session.speed_r': np.float64(2.24956148437523)}
   {'id': '100083_20110727T140025', 'discrete.speed_r': np.float64(1.76114547183087), 'session.speed_r': np.float64(1.7612)}
   {'id': '100090_20100120T100603', 'discrete.speed_r': np.float64(2.72384572821508), 'session.speed_r': np.float64(2.7239)}
   {'id': '100091_20110803T100338', 'discrete.speed_r': np.float64(2.26434790960304), 'session.speed_r': np.float64(2.2644)}
   {'id': '100115_20100330T103733', 'discrete.speed_r': np.float64(2.50204909421317), 'session.speed_r': np.float64(2.5021)}

## Get statistics for base data

In [41]:
base_data = loader.get_discrete_with_metadata()
base_data.head()

,ID,Speed_Output,Label,Hz,Step_Width_Left,Step_Width_Right,Stride_Rate_Left,Stride_Rate_Right,Stride_Length_Left,Stride_Length_Right,...,injury_desc,injury2_desc,injury_name,injury2_name,injured_joint_code,injured_joint2_code,injured_side_code,injured_side2_code,has_no_injury,is_injured
0,100001_20110531T161051,2.489233,run,200,0.123419,0.123419,78.947368,78.947368,1.891817,1.891817,...,Inflammation or irritation of Achilles tendon ...,No injury has been diagnosed.,achilles tendonitis,no injury,ankle,no_injury,left,right,False,True
1,100002_20110601T140505,2.722687,run,200,0.032922,0.032922,81.632653,81.632653,2.001175,2.001175,...,Painful friction of iliotibial band rubbing ov...,No injury has been diagnosed.,itb syndrome,no injury,thigh,no_injury,right,right,False,True
2,100003_20110601T095930,2.949904,run,200,0.097273,0.097273,78.947368,78.947368,2.241927,2.241927,...,Pain around kneecap caused by poor tracking an...,General sensation of discomfort without speci...,patellofemoral pain syndrome,pain,knee,foot,left,left,False,True
3,100004_20110203T120721,2.688014,run,200,0.011401,0.011401,82.191781,82.191781,1.962250,1.962250,...,Overstretching or tearing of the calf muscle f...,No injury has been diagnosed.,calf muscle strain,no injury,lower_leg,no_injury,right,right,False,True
4,100004_20140929T102035,2.928598,run,200,0.029021,0.029021,83.333333,82.758621,2.108590,2.123233,...,No injury has been diagnosed.,No injury has been diagnosed.,no injury,no injury,no_injury,no_injury,no_injury,no_injury,True,False

In [42]:
missing_percent = base_data.isnull().mean() * 100
print("Percentage of missing values per column:")
with pd.option_context("display.max_rows", None):
    display(missing_percent.sort_values(ascending=False))

Percentage of missing values per column:

YrPR                              77.164920
RaceTimeSecs                      75.951462
NumRaces                          72.917816
RaceTimeHrs                       70.049641
RaceTimeMins                      62.051848
YrsRunning                        31.163817
DominantLeg                       19.415334
RaceDistance                      18.643133
Activities                        17.429675
Level                             14.837286
injury_severity_value              4.412576
injury_severity_code               4.412576
r_vertical_oscillation             0.661886
Vertical_Oscillation_Left          0.661886
l_vertical_oscillation             0.661886
Vertical_Oscillation_Right         0.661886
datestring                         0.551572
Height                             0.441258
Weight                             0.275786
Gender                             0.055157
age                                0.055157
l_ankle_eve_peak_angle             0.000000
l_knee_abd_peak_vel                0.000000
l_hip_rot_excursion                0.000000
l_foot_prog_angle                  0.000000
l_foot_ang_at_hs                   0.000000
l_mhw_exc_from_to                  0.000000
l_ankle_eve_peak_vel               0.000000
l_ankle_rot_peak_vel               0.000000
l_knee_rot_peak_vel                0.000000
l_knee_add_peak_vel                0.000000
l_hip_abd_peak_vel                 0.000000
l_hip_add_excursion                0.000000
l_hip_rot_peak_vel                 0.000000
l_pronation_onset                  0.000000
l_pronation_offset                 0.000000
l_peak_hip_add_velocity            0.000000
l_hip_rot_peak_angle               0.000000
l_knee_rot_excursion               0.000000
l_hip_add_peak_angle               0.000000
l_hip_ext_peak_angle               0.000000
l_ankle_df_peak_angle              0.000000
l_knee_rot_peak_angle              0.000000
l_knee_abd_excursion               0.000000
l_knee_abd_peak_angle              0.000000
l_knee_add_excursion               0.000000
l_knee_add_peak_angle              0.000000
l_knee_flex_peak_angle             0.000000
l_pelvis_peak_drop_angle           0.000000
l_pelvis_drop_excursion            0.000000
l_ankle_rot_excursion              0.000000
l_ankle_rot_peak_angle             0.000000
l_ankle_eve_excursion              0.000000
l_ankle_eve_percent_stance         0.000000
l_peak_pelvic_drop_velocity        0.000000
r_stride_rate                      0.000000
r_step_width                       0.000000
r_peak_pelvic_drop_velocity        0.000000
r_ankle_eve_peak_vel               0.000000
r_ankle_rot_peak_vel               0.000000
r_knee_abd_peak_vel                0.000000
r_knee_add_peak_vel                0.000000
r_hip_abd_peak_vel                 0.000000
r_knee_rot_peak_vel                0.000000
r_hip_rot_peak_vel                 0.000000
r_pronation_onset                  0.000000
r_pronation_offset                 0.000000
r_peak_hip_add_velocity            0.000000
injury_code                        0.000000
r_foot_ang_at_hs                   0.000000
injury2_code                       0.000000
injury_desc                        0.000000
injury2_desc                       0.000000
injury_name                        0.000000
injury2_name                       0.000000
injured_joint_code                 0.000000
injured_joint2_code                0.000000
injured_side_code                  0.000000
injured_side2_code                 0.000000
has_no_injury                      0.000000
r_mhw_exc_from_to                  0.000000
r_foot_prog_angle                  0.000000
l_swing_time                       0.000000
r_ankle_rot_excursion              0.000000
r_stride_length                    0.000000
r_swing_time                       0.000000
r_stance_time                      0.000000
r_pelvis_peak_drop_angle           0.000000
r_pelvis_drop_excursion            0.000000
r_ankle_df_peak_angle              0.000000
r_ankle_eve_peak_angle             0.000000
r_ankle_eve_percent_stance         0.000000
r_ankle_eve_excursion              0.000000
r_ankle_rot_peak_angle             0.000000
r_knee_flex_peak_angle             0.000000
r_hip_rot_excursion                0.000000
r_knee_add_peak_angle              0.000000
r_knee_add_excursion               0.000000
r_knee_abd_peak_angle              0.000000
r_knee_abd_excursion               0.000000
r_knee_rot_peak_angle              0.000000
r_knee_rot_excursion               0.000000
r_hip_ext_peak_angle               0.000000
r_hip_add_peak_angle               0.000000
r_hip_add_excursion                0.000000
r_hip_rot_peak_angle               0.000000
l_stance_time                      0.000000
ID                                 0.000000
l_stride_length                    0.000000
Ankle_Eve_Percent_Stance_Right     0.000000
Ankle_Eve_Excursion_Right          0.000000
Ankle_Rot_Peak_Angle_Left          0.000000
Ankle_Rot_Peak_Angle_Right         0.000000
Ankle_Rot_Excursion_Left           0.000000
Ankle_Rot_Excursion_Right          0.000000
Knee_Flex_Peak_Angle_Left          0.000000
Knee_Flex_Peak_Angle_Right         0.000000
Knee_Add_Peak_Angle_Left           0.000000
Knee_Add_Peak_Angle_Right          0.000000
Knee_Add_Excursion_Left            0.000000
Knee_Add_Excursion_Right           0.000000
Knee_Abd_Peak_Angle_Left           0.000000
Knee_Abd_Peak_Angle_Right          0.000000
Knee_Abd_Excursion_Left            0.000000
Knee_Abd_Excursion_Right           0.000000
Knee_Rot_Peak_Angle_Left           0.000000
Knee_Rot_Peak_Angle_Right          0.000000
Knee_Rot_Excursion_Left            0.000000
Knee_Rot_Excursion_Right           0.000000
Ankle_Eve_Excursion_Left           0.000000
Ankle_Eve_Percent_Stance_Left      0.000000
l_stride_rate                      0.000000
Ankle_Eve_Peak_Angle_Right         0.000000
Label                              0.000000
Hz                                 0.000000
Step_Width_Left                    0.000000
Step_Width_Right                   0.000000
Stride_Rate_Left                   0.000000
Stride_Rate_Right                  0.000000
Stride_Length_Left                 0.000000
Stride_Length_Right                0.000000
Swing_Time_Left                    0.000000
Swing_Time_Right                   0.000000
Stance_Time_Left                   0.000000
Stance_Time_Right                  0.000000
Pelvis_Peak_Drop_Angle_Left        0.000000
Pelvis_Peak_Drop_Angle_Right       0.000000
Pelvis_Drop_Excursion_Left         0.000000
Pelvis_Drop_Excursion_Right        0.000000
Ankle_DF_Peak_Angle_Left           0.000000
Ankle_DF_Peak_Angle_Right          0.000000
Ankle_Eve_Peak_Angle_Left          0.000000
Hip_Ext_Peak_Angle_Left            0.000000
Hip_Ext_Peak_Angle_Right           0.000000
Hip_Add_Peak_Angle_Left            0.000000
Hip_Add_Peak_Angle_Right           0.000000
Knee_Rot_Peak_Vel_Left             0.000000
Knee_Rot_Peak_Vel_Right            0.000000
Hip_Rot_Peak_Vel_Left              0.000000
Hip_Rot_Peak_Vel_Right             0.000000
Pronation_Onset_Left               0.000000
Pronation_Onset_Right              0.000000
Supination_Timing_Left             0.000000
Supination_Timing_Right            0.000000
Hip_Add_Peak_Vel_Left              0.000000
Hip_Add_Peak_Vel_Right             0.000000
Pelvic_Drop_Peak_Vel_Left          0.000000
Pelvic_Drop_Peak_Vel_Right         0.000000
id                                 0.000000
sub_id                             0.000000
filename                           0.000000
speed_r                            0.000000
Speed_Output                       0.000000
session_file_path                  0.000000
l_step_width                       0.000000
Hip_Abd_Peak_Vel_Right             0.000000
Hip_Abd_Peak_Vel_Left              0.000000
Knee_Add_Peak_Vel_Right            0.000000
Foot_Ang_At_HS_Left                0.000000
Hip_Add_Excursion_Left             0.000000
Hip_Add_Excursion_Right            0.000000
Hip_Rot_Peak_Angle_Left            0.000000
Hip_Rot_Peak_Angle_Right           0.000000
Hip_Rot_Excursion_Left             0.000000
Hip_Rot_Excursion_Right            0.000000
Foot_Prog_Angle_Left               0.000000
Foot_Prog_Angle_Right              0.000000
Foot_Ang_At_HS_Right               0.000000
Knee_Add_Peak_Vel_Left             0.000000
MHW_Exc_From_TO_Left               0.000000
MHW_Exc_From_TO_Right              0.000000
Ankle_Eve_Peak_Vel_Left            0.000000
Ankle_Eve_Peak_Vel_Right           0.000000
Ankle_Rot_Peak_Vel_Left            0.000000
Ankle_Rot_Peak_Vel_Right           0.000000
Knee_Abd_Peak_Vel_Left             0.000000
Knee_Abd_Peak_Vel_Right            0.000000
is_injured                         0.000000
dtype: float64

In [43]:
base_data["is_injured"].value_counts(normalize=True)

is_injured
True     0.634859
False    0.365141
Name: proportion, dtype: float64

In [47]:
len(base_data["sub_id"].unique())
# Count how many subjects (sub_id) have more than one row in base_data
subject_counts = base_data["sub_id"].value_counts()
num_subjects_with_multiple_rows = (subject_counts > 1).sum()
print(f"Number of subjects with more than one row: {num_subjects_with_multiple_rows}")

Number of subjects with more than one row: 207

## Verification that tabular X and Y test and train are okay

In [49]:
X_train: pd.DataFrame = pd.read_csv(c.RICKD_MODEL_1_X_TRAIN_FILE_40_FEATURES, index_col=0)
y_train: pd.DataFrame = pd.read_csv(c.RICKD_MODEL_1_Y_TRAIN_FILE, index_col=0)
X_test: pd.DataFrame = pd.read_csv(c.RICKD_MODEL_1_X_TEST_FILE_40_FEATURES, index_col=0)
y_test: pd.DataFrame = pd.read_csv(c.RICKD_MODEL_1_Y_TEST_FILE, index_col=0)

print(f"X_train shape: {X_train.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_test shape: {y_test.shape}")

X_train shape: (1154, 40)
y_train shape: (1154, 1)
X_test shape: (287, 40)
y_test shape: (287, 1)

In [ ]:
train_data = pd.concat([X_train, y_train], axis=1)
test_data = pd.concat([X_test, y_test], axis=1)
all_data = pd.concat([train_data, test_data], axis=0)
all_data.info()
all_data.head()

<class 'pandas.core.frame.DataFrame'>
Index: 1441 entries, 100001_20110531T161051 to 201101_20150413T143152
Data columns (total 41 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   age                                    1441 non-null   float64
 1   height                                 1441 non-null   float64
 2   dom_leg_diff_ankle_df_peak_angle       1441 non-null   float64
 3   dom_leg_ankle_eve_peak_angle           1441 non-null   float64
 4   dom_leg_diff_ankle_eve_peak_angle      1441 non-null   float64
 5   dom_leg_ankle_eve_peak_vel             1441 non-null   float64
 6   dom_leg_diff_ankle_eve_peak_vel        1441 non-null   float64
 7   dom_leg_diff_ankle_eve_percent_stance  1441 non-null   float64
 8   dom_leg_diff_ankle_rot_excursion       1441 non-null   float64
 9   dom_leg_diff_ankle_rot_peak_angle      1441 non-null   float64
 10  dom_leg_foot_ang_at_hs                 1441 non-null   float64
 11  dom_leg_diff_foot_ang_at_hs            1441 non-null   float64
 12  dom_leg_diff_hip_abd_peak_vel          1441 non-null   float64
 13  dom_leg_diff_hip_add_peak_angle        1441 non-null   float64
 14  dom_leg_diff_hip_add_peak_vel          1441 non-null   float64
 15  dom_leg_hip_ext_peak_angle             1441 non-null   float64
 16  dom_leg_diff_hip_ext_peak_angle        1441 non-null   float64
 17  dom_leg_hip_rot_peak_angle             1441 non-null   float64
 18  dom_leg_diff_hip_rot_peak_angle        1441 non-null   float64
 19  dom_leg_hip_rot_peak_vel               1441 non-null   float64
 20  dom_leg_diff_hip_rot_peak_vel          1441 non-null   float64
 21  dom_leg_diff_knee_add_excursion        1441 non-null   float64
 22  dom_leg_diff_knee_add_peak_vel         1441 non-null   float64
 23  dom_leg_knee_flex_peak_angle           1441 non-null   float64
 24  dom_leg_knee_rot_excursion             1441 non-null   float64
 25  dom_leg_knee_rot_peak_angle            1441 non-null   float64
 26  dom_leg_knee_rot_peak_vel              1441 non-null   float64
 27  dom_leg_diff_knee_rot_peak_vel         1441 non-null   float64
 28  dom_leg_mhw_exc_from_to                1441 non-null   float64
 29  dom_leg_diff_mhw_exc_from_to           1441 non-null   float64
 30  dom_leg_pelvic_drop_peak_vel           1441 non-null   float64
 31  dom_leg_diff_pelvic_drop_peak_vel      1441 non-null   float64
 32  dom_leg_diff_pelvis_drop_excursion     1441 non-null   float64
 33  dom_leg_diff_stance_time               1441 non-null   float64
 34  dom_leg_step_width                     1441 non-null   float64
 35  dom_leg_stride_length                  1441 non-null   float64
 36  dom_leg_diff_stride_rate               1441 non-null   float64
 37  dom_leg_supination_timing              1441 non-null   float64
 38  dom_leg_vertical_oscillation           1441 non-null   float64
 39  dom_leg_diff_vertical_oscillation      1441 non-null   float64
 40  is_injured                             1441 non-null   bool
dtypes: bool(1), float64(40)
memory usage: 463.0+ KB

,age,height,dom_leg_diff_ankle_df_peak_angle,dom_leg_ankle_eve_peak_angle,dom_leg_diff_ankle_eve_peak_angle,dom_leg_ankle_eve_peak_vel,dom_leg_diff_ankle_eve_peak_vel,dom_leg_diff_ankle_eve_percent_stance,dom_leg_diff_ankle_rot_excursion,dom_leg_diff_ankle_rot_peak_angle,...,dom_leg_diff_pelvic_drop_peak_vel,dom_leg_diff_pelvis_drop_excursion,dom_leg_diff_stance_time,dom_leg_step_width,dom_leg_stride_length,dom_leg_diff_stride_rate,dom_leg_supination_timing,dom_leg_vertical_oscillation,dom_leg_diff_vertical_oscillation,is_injured
id,,,,,,,,,,,,,,,,,,,,,
100001_20110531T161051,0.727682,-0.058148,0.633105,1.447539,0.504055,1.352344,0.367857,-0.230089,0.814120,-1.231183,...,-0.964662,1.499872,-1.080393,1.983425,-0.244786,-0.024152,0.518204,0.557382,0.334735,True
100002_20110601T140505,-0.150620,0.088511,-0.769343,-0.891457,-0.128827,0.772460,1.501485,0.540020,0.693086,0.001899,...,0.280063,1.441758,-1.778995,-0.857244,0.103879,-0.024152,-0.383164,-0.052167,-1.015686,True
100004_20110203T120721,-0.326281,0.318975,-0.611548,0.952733,0.213660,-0.265570,-0.682724,-0.340104,0.177909,1.795760,...,-0.465172,1.362814,1.364717,-1.532790,-0.020226,-0.024152,-1.184380,0.321218,0.936946,True
100004_20140929T102035,0.025040,0.256121,-0.597585,-1.235893,-0.149788,-1.023207,-1.082561,0.209973,-0.218022,0.917178,...,1.031569,1.266941,0.666114,-0.979693,0.446352,2.242683,-1.284532,0.006865,1.274719,False
100005_20110208T120837,-0.501941,-1.336177,-0.055702,-0.082042,-0.504754,0.652176,-0.658743,-0.670150,-0.799613,-0.040992,...,-0.513202,0.073574,-0.032488,-0.415119,-0.653740,-0.024152,-1.484836,-1.061532,-0.356889,True

In [54]:
all_data["id"] = all_data.index
all_data["sub_id"] = all_data["id"].str.split("_").str[0]
all_data.head()

,age,height,dom_leg_diff_ankle_df_peak_angle,dom_leg_ankle_eve_peak_angle,dom_leg_diff_ankle_eve_peak_angle,dom_leg_ankle_eve_peak_vel,dom_leg_diff_ankle_eve_peak_vel,dom_leg_diff_ankle_eve_percent_stance,dom_leg_diff_ankle_rot_excursion,dom_leg_diff_ankle_rot_peak_angle,...,dom_leg_diff_stance_time,dom_leg_step_width,dom_leg_stride_length,dom_leg_diff_stride_rate,dom_leg_supination_timing,dom_leg_vertical_oscillation,dom_leg_diff_vertical_oscillation,is_injured,id,sub_id
id,,,,,,,,,,,,,,,,,,,,,
100001_20110531T161051,0.727682,-0.058148,0.633105,1.447539,0.504055,1.352344,0.367857,-0.230089,0.814120,-1.231183,...,-1.080393,1.983425,-0.244786,-0.024152,0.518204,0.557382,0.334735,True,100001_20110531T161051,100001
100002_20110601T140505,-0.150620,0.088511,-0.769343,-0.891457,-0.128827,0.772460,1.501485,0.540020,0.693086,0.001899,...,-1.778995,-0.857244,0.103879,-0.024152,-0.383164,-0.052167,-1.015686,True,100002_20110601T140505,100002
100004_20110203T120721,-0.326281,0.318975,-0.611548,0.952733,0.213660,-0.265570,-0.682724,-0.340104,0.177909,1.795760,...,1.364717,-1.532790,-0.020226,-0.024152,-1.184380,0.321218,0.936946,True,100004_20110203T120721,100004
100004_20140929T102035,0.025040,0.256121,-0.597585,-1.235893,-0.149788,-1.023207,-1.082561,0.209973,-0.218022,0.917178,...,0.666114,-0.979693,0.446352,2.242683,-1.284532,0.006865,1.274719,False,100004_20140929T102035,100004
100005_20110208T120837,-0.501941,-1.336177,-0.055702,-0.082042,-0.504754,0.652176,-0.658743,-0.670150,-0.799613,-0.040992,...,-0.032488,-0.415119,-0.653740,-0.024152,-1.484836,-1.061532,-0.356889,True,100005_20110208T120837,100005

In [ ]:
# Ensure 'id' is a column in both DataFrames and set as index for comparison
all_data_compare = all_data.set_index("id")
base_data_compare = base_data.set_index("id")

# Align indices for intersection only
common_ids = all_data_compare.index.intersection(base_data_compare.index)

# Extract is_injured for common ids
all_data_is_injured = all_data_compare.loc[common_ids, "is_injured"]
base_data_is_injured = base_data_compare.loc[common_ids, "is_injured"]

# Compare values
comparison = all_data_is_injured == base_data_is_injured

# Print summary
num_mismatches = (~comparison).sum()
print(f"Number of mismatches in 'is_injured' between all_data and base_data: {num_mismatches}")
if num_mismatches > 0:
    mismatched_ids = comparison[~comparison].index.tolist()
    print("Mismatched IDs (showing up to 10):", mismatched_ids[:10])

Number of mismatches in 'is_injured' between all_data and base_data: 0